# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# SPDX-License-Identifier: curl
---
# https://clang.llvm.org/extra/clang-tidy/checks/list.html

Checks:
  - -clang-analyzer-optin.performance.Padding
  - -clang-analyzer-security.ArrayBound  # due to false positives with clang-tidy v21.1.0
  - -clang-analyzer-security.insecureAPI.bzero  # for FD_ZERO() (seen on macOS)
  - -clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling
  - -clang-diagnostic-nullability-extension
  - bugprone-suspicious-realloc-usage
  - misc-const-correctness
  - portability-*
  - readability-named-parameter
  - readability-redundant-control-flow
  - readability-redundant-preprocessor
  - readability-uppercase-literal-suffix
