# Copyright (C) Viktor Szakats
#
# SPDX-License-Identifier: curl

# https://cmake-format.readthedocs.io/en/latest/cmake-lint.html
# https://github.com/cheshirekow/cmake_format/blob/master/cmakelang/configuration.py

# Options affecting formatting
format:
  # Disable formatting entirely, making cmake-format a no-op
  disable: false
  # How wide to allow formatted cmake files
  line_width: 132
  # How many spaces to tab for indent
  tab_size: 2
  # If true, lines are indented using tab characters (utf-8 0x09) instead of <tab_size> space characters (utf-8 0x20).
  # In cases where the layout would require a fractional tab character, the behavior of the fractional indentation is
  # governed by <fractional_tab_policy>
  use_tabchars: false

# Options affecting the linter
lint:
  # a list of lint codes to disable
  disabled_codes: ['C0113']
  # regular expression pattern describing valid function names
  function_pattern: 'curl_[0-9a-z_]+'
  # regular expression pattern describing valid macro names
  macro_pattern: '(curl_[0-9a-z_]+|check_include_file_concat_curl)'
  # regular expression pattern describing valid names for variables with global (cache) scope
  global_var_pattern: '[A-Z][0-9A-Z_]+'
  # regular expression pattern describing valid names for variables with global scope (but internal semantic)
  internal_var_pattern: '_[a-z][0-9a-z_]+'
  # regular expression pattern describing valid names for
  # variables with local scope
  local_var_pattern: '_[a-z][a-z0-9_]+'
  # regular expression pattern describing valid names for privatedirectory variables
  private_var_pattern: '_[0-9a-z_]+'
  # regular expression pattern describing valid names for public directory variables
  public_var_pattern: '([A-Z][0-9A-Z_]+|[A-Z][A-Za-z0-9]+_FOUND|[a-z]+_SOURCES|prefix|exec_prefix|includedir|libdir|ssize_t|_FILE_OFFSET_BITS)'
  # regular expression pattern describing valid names for function/macro arguments and loop variables.
  argument_var_pattern: '_[a-z][a-z0-9_]+'
  # regular expression pattern describing valid names for keywords used in functions or macros
  keyword_pattern: '[A-Z][0-9A-Z_]+'
  # In the heuristic for C0201, how many conditionals to match within a loop in before considering the loop a parser.
  max_conditionals_custom_parser: 2
  # Require at least this many newlines between statements
  min_statement_spacing: 1
  # Require no more than this many newlines between statements
  max_statement_spacing: 2
  max_returns: 6
  max_branches: 12
  max_arguments: 5
  max_localvars: 15
  max_statements: 50

# Options affecting file encoding
encode:
  # Specify the encoding of the input file. Defaults to utf-8
  input_encoding: 'utf-8'
