#***************************************************************************
#                                  _   _ ____  _
#  Project                     ___| | | |  _ \| |
#                             / __| | | | |_) | |
#                            | (__| |_| |  _ <| |___
#                             \___|\___/|_| \_\_____|
#
# Copyright (C) 1998 - 2022, Daniel Stenberg, <daniel@haxx.se>, et al.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at https://curl.se/docs/copyright.html.
#
# You may opt to use, copy, modify, merge, publish, distribute and/or sell
# copies of the Software, and permit persons to whom the Software is
# furnished to do so, under the terms of the COPYING file.
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
# KIND, either express or implied.
#
# SPDX-License-Identifier: curl
#
###########################################################################
extraction:
  cpp:
    prepare:
      packages: # to avoid confusion with libopenafs-dev which also provides a des.h
        - libssl-dev
    after_prepare: # make sure lgtm.com doesn't use CMake (which generates and runs tests)
      - rm -f CMakeLists.txt
      - autoreconf -fi
    configure: # enable as many optional features as possible
      command: ./configure --enable-ares --with-libssh2 --with-gssapi --with-librtmp --with-openssl
