#***************************************************************************
#                                  _   _ ____  _
#  Project                     ___| | | |  _ \| |
#                             / __| | | | |_) | |
#                            | (__| |_| |  _ <| |___
#                             \___|\___/|_| \_\_____|
#
# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at https://curl.se/docs/copyright.html.
#
# You may opt to use, copy, modify, merge, publish, distribute and/or sell
# copies of the Software, and permit persons to whom the Software is
# furnished to do so, under the terms of the COPYING file.
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
# KIND, either express or implied.
#
# SPDX-License-Identifier: curl
#
###########################################################################

# https://ci.appveyor.com/project/curlorg/curl/history
# AppVeyor configuration:
#   https://www.appveyor.com/docs/appveyor-yml/
# AppVeyor worker images:
#   https://www.appveyor.com/docs/windows-images-software/

version: 7.50.0.{build}

environment:
  DO_NOT_TRACK: '1'

  matrix:
    # CMake Visual Studio builds

    - job_name: 'CM VS2022, Release, x64, OpenSSL 3.5, Shared, Build-tests'
      APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2022'
      CMAKE_GENERATOR: 'Visual Studio 17 2022'
      CMAKE_GENERATE: '-A x64 -DCURL_USE_SCHANNEL=OFF -DCURL_USE_OPENSSL=ON'

    - job_name: 'CM VS2019, Debug, x64, OpenSSL 3.0 + Schannel, Shared, !verbose, Build-tests'
      APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2019'
      CMAKE_GENERATOR: 'Visual Studio 16 2019'
      CMAKE_GENERATE: '-A x64 -DENABLE_DEBUG=ON -DCURL_USE_OPENSSL=ON -DCURL_DISABLE_VERBOSE_STRINGS=ON'

    # temp
    - job_name: 'CM VS2019, Release, x64, OpenSSL 3.0 + Schannel, Shared, !verbose, Build-tests'
      APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2019'
      CMAKE_GENERATOR: 'Visual Studio 16 2019'
      CMAKE_GENERATE: '-A x64 -DCURL_USE_OPENSSL=ON -DCURL_DISABLE_VERBOSE_STRINGS=ON'

    # temp
    - job_name: 'CM VS2019, Release, x86, OpenSSL 3.0 + Schannel, Shared, !verbose, Build-tests'
      APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2019'
      CMAKE_GENERATOR: 'Visual Studio 16 2019'
      CMAKE_GENERATE: '-A Win32 -DCURL_USE_OPENSSL=ON -DCURL_DISABLE_VERBOSE_STRINGS=ON'

install:
  - ps: $env:PATH = "C:/msys64/usr/bin;$env:PATH"

build_script:
  - cmd: sh -c ./appveyor.sh

clone_depth: 10

# select branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master
    - /\/ci$/

skip_commits:
  files:
    - '.circleci/*'
    - '.github/**/*'
    - 'Dockerfile'
    - 'projects/OS400/*'
    - 'projects/vms/*'

#artifacts:
#  - path: '**/curl.exe'
#    name: curl
#  - path: '**/*.dll'
#    name: libcurl dll
#  - path: '**/*.lib'
#    name: libcurl lib
