#!/bin/sh

die(){
	echo "$@"
	exit
}

aclocal           || die "The command 'aclocal' failed"
autoheader        || die "The command 'autoheader' failed"
autoconf          || die "The command 'autoconf' failed"
automake          || die "The command 'automake $MAKEFILES' failed"
