#!/bin/sh
#
# $Id$
#
# re autoconf/automake shell script
#

die(){
	echo "$@" ; exit
}

aclocal -I . -I m4 || die "The command 'aclocal -I . -I m4' failed"
autoheader   || die "The command 'autoheader' failed"
automake     || die "The command 'automake' failed"
autoconf     || die "The command 'autoconf' failed"
