#***************************************************************************
#                                  _   _ ____  _
#  Project                     ___| | | |  _ \| |
#                             / __| | | | |_) | |
#                            | (__| |_| |  _ <| |___
#                             \___|\___/|_| \_\_____|
#
# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at https://curl.se/docs/copyright.html.
#
# You may opt to use, copy, modify, merge, publish, distribute and/or sell
# copies of the Software, and permit persons to whom the Software is
# furnished to do so, under the terms of the COPYING file.
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
# KIND, either express or implied.
#
# SPDX-License-Identifier: curl
#
###########################################################################

SRC ?= https.c

# What to call the final executable
TARGET ?= example

# What compiler to use
CC ?= gcc

# Compiler flags, -g for debug
CFLAGS ?= -g

# This should point to a directory that holds libcurl, if it is not in the
# system's standard lib dir
# We also set a -L to include the directory where we have the OpenSSL libraries
LDFLAGS ?= -L/usr/lib -L/usr/local/lib

# We need -lsocket and -lnsl when on Solaris
# We need -lssl and -lcrypto when using libcurl with TLS support
# We need -lpthread for the pthread example
LIBS ?= -lssl -lcrypto
# We need -lcurl for the curl stuff
LIBS := -lcurl $(LIBS)

# Link the target with all objects and libraries
$(TARGET) : $(SRC)
	$(CC) $< $(CFLAGS) $(LDFLAGS) $(LIBS) -o $(TARGET)
