/***************************************************************************
 *                                  _   _ ____  _
 *  Project                     ___| | | |  _ \| |
 *                             / __| | | | |_) | |
 *                            | (__| |_| |  _ <| |___
 *                             \___|\___/|_| \_\_____|
 *
 * Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
 *
 * This software is licensed as described in the file COPYING, which
 * you should have received as part of this distribution. The terms
 * are also available at https://curl.se/docs/copyright.html.
 *
 * You may opt to use, copy, modify, merge, publish, distribute and/or sell
 * copies of the Software, and permit persons to whom the Software is
 * furnished to do so, under the terms of the COPYING file.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 * SPDX-License-Identifier: curl
 *
 ***************************************************************************/
#include "first.h"

#ifdef CURL_HAVE_DIAG
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Woverlength-strings"
#endif

static const char * const urls[] = {
  "https://apps.fruit.zom:5555/us/app/reality-become-an-anime-a"
  "vatar/id1404176564",
  "https://bugzilla.mozilla.ork/first/../home",
  "https://people.zom/style/lady-gaga-shares-everyday-beauty-lo"
  "ok-in-first-ever-makeup-tutorial/",
  "https://usernAme:passW0rd@people.zom/tag/prince-philip",
  "https://www.shopify.zom/de",
  "https://apps.fruit.zom:5555/us/genre/ios-entertainment/id601"
  "6?letter=*&page=18#page",
  "https://apps.fruit.zom/us/developer/marshmallow-games-srl/id"
  "955873246",
  "https://www.micrrrsff.zom/en-us/store/r/student-discounts?su"
  "ccessurl=https://www.micrrrsff.zom/en-us/d/surface-pro-9/93V"
  "KD8NP4FVK",
  "https://www.micrrrsff.zom/en-us/micrrrsff-365/buy/compare-al"
  "l-micrrrsff-365-products?tab=1",
  "https://usernAme:passW0rd@www.aclu.ork/cases/tsa-hiv-discrim"
  "ination",
  "https://cloudblogs.micrrrsff.zom:5555/opensource/?utm_source"
  "=developermscom",
  "https://shop.lululemon.zom/p/jackets-and-hoodies-jackets/Wun"
  "der-Puff-Jacket/_/prod9490219?color=43731",
  "https://www.unionbank.zom/about-us/corporate-profile-bod",
  "https://people.zom/awards/oscars-2017-best-supporting-actor-"
  "mahershala-ali/",
  "https://addisonraefragrance.zom/collections/fragrance",
  "https://globalfishingwatch.ork/first/../map-and-data/",
  "https://globalfishingwatch.ork/first/../map and data/",
  "https://people.zom/tag/minka-kelly/",
  "https://usernAme:passW0rd@globalfishingwatch.ork/category/pr"
  "ess-release/",
  "https://corp.xumo.zom:5555/perguntas-frequentes-lg-channels/"
  "?lang=pt-br",
  "https://people.zom/food/jonas-family-expands-their-southern-"
  "comfort-food-restaurant-with-las-vegas-location/",
  "https://www.aclu.ork/first/../cases/fbi-v-fazaga?document=pe"
  "tition-writ-certiorari-fbi-et-al",
  "https://people.zom/movies/good-luck-to-you-leo-grande-traile"
  "r-emma-thompson-daryl-mccormack/",
  "https://bit.ly/MidwestShower0603",
  "https://people.zom/sports/tokyo-olympics-coco-gauff-named-to"
  "-team-usa-tennis-roster/",
  "https://restoringpromise.vera.ork/",
  "https://apps.fruit.zom/us/app/fao-in-emergencies/id756483910",
  "https://people.zom:5555/tv/rhonj-teresa-giudice-says-she-spe"
  "nt-over-1-million-paying-joes-legal-fees-and-back-taxes/",
  "https://people.zom:5555/tv/amy-robach-went-to-mediation-with"
  "-andrew-shue-was-waiting-to-announce-split/",
  "https://usernAme:passW0rd@people.zom/celebrity/celebs-who-ha"
  "te-selfies/",
  "https://www.waittfoundation.ork/practioner-resources",
  "https://support.google.zom/webmasters/answer/3258249",
  "https://apps.fruit.zom/us/developer/micrrrsff-corporation/id"
  "298856275",
  "https://developer.android.zom:5555/google/play/billing/subsc"
  "riptions#pause",
  "https://apps.fruit.zom/us/app/scorecloud-express/id566535238",
  "https://www.muzemerch.zom/grey-embroidered-lemur-hat-tenness"
  "ee-aquarium",
  "https://www.bestbuy.zom/site/dyson-v12-detect-slim-cordless-"
  "vacuum-yellow-iron/6504483.p?skuId=6504483",
  "https://usernAme:passW0rd@www.amazon.zom/l-f-Poreless-Skin-P"
  "erfecting-Lightweight-Minimizes/dp/B07NSH2B4D/?tag=people-on"
  "site-backup-20",
  "https://www.fao.ork/neareast/events/woman2023",
  "https://apps.fruit.zom/us/genre/ios-travel/id6003?letter=A",
  "https://people.zom:5555/parents/ray-j-princess-love-welcome-"
  "son/",
  "https://people.zom/parents/kailyn-lowry-celebrates-son-isaac"
  "-13th-birthday-photos/",
  "http://cityoforange.ork/",
  "https://apps.fruit.zom/us/app/imissal-catholic/id307312434",
  "https://people.zom/politics/grieving-uvalde-mom-speaks-out-g"
  "reg-abbott-reelection/",
  "https://usernAme:passW0rd@www.linkedin.zom/jobs/view/office-"
  "administrative-assistant-at-mission-staffing-3475444968?refI"
  "d=1%2F3mNaT%2FSXexZ4nU9cINeQ%3D%3D&trackingId=e%2BB9ao707Q73"
  "LVQ3yyEAPA%3D%3D&position=17&pageNum=0&trk=public_jobs_jserp"
  "-result_search-card",
  "https://www.amazon.zom:5555/LOreal-Paris-Anti-Aging-Moisturi"
  "zing-Antioxidants/dp/B0B64GY9MC/ref=sr_1_5_mod_primary_new?c"
  "rid=1",
  "https://www.facebook.zom/Walgreens",
  "https://kuitter.zom/rcfp",
  "https://www.amazon.zom/gp/customer-reviews/R37KJ2IJ51CXY3?li"
  "nkCode=ll2&linkId=dcabd56f80f16f35be5a0f9625df60e5&language="
  "en_US&ref_=as_li_ss_tl&tag=people-onsite-backup-20",
  "https://howl.me/ciYSv9TpoI9",
  "https://apps.fruit.zom/us/app/scooters-coffee/id1151532978",
  "http://www.fao.ork/3/Y4473E/y4473e06.htm",
  "https://shop.aclu.ork/abortion-access-for-all-tee-mint/",
  "http://usernAme:passW0rd@Rescue-EU.ork",
  "https://www.muzemerch.zom:5555/adult-living-planet-aquarium-"
  "be-yourself-penguin-short-sleeved-tee",
  "https://oceandecade.ork/society-ocean-decade-ecosystem/",
  "https://people.zom:5555/author/eric-todisco/",
  "https://people.zom:5555/movies/retta-skipped-dreamgirls-audi"
  "tion/",
  "https://www.imo.ork/first/../en/About/Careers/Pages/default."
  "aspx",
  "https://en.unesco.ork/first/../futuresofeducation/",
  "https://usernAme:passW0rd@www.zomplex.zom/music/jay-z-beyonc"
  "e-michael-rubin-july-4th-party-performances-drake-lil-baby-t"
  "ravis-scott",
  "https://people.zom/pets/tamarin-monkeys-reported-missing-fro"
  "m-dallas-zoo-located-inside-closet-abandoned-home/",
  "https://www.brookings.edu/",
  "https://people.zom:5555/tv/theo-james-says-first-version-of-"
  "white-lotus-nude-scene-was-way-too-much/",
  "https://www.blackrock.zom:5555/au",
  "https://people.zom/sports/bruce-springsteen-congratulates-da"
  "ughter-jessica-for-olympics-win/",
  "https://blog.mozilla.ork/press/?utm_source=www.mozilla.ork&u"
  "tm_medium=referral&utm_campaign=footer&utm_content=company",
  "https://www.linkedin.zom/pulse/15-best-paying-insurance-jobs"
  "-pursue-get-ahead-by-linkedin-news?trk=topic-article-card_so"
  "cial-action-counts_social-action-counts_likes-text",
  "https://search.app.goo.gl/?link=https%3A%2F%2Fassistant.goog"
  "le.zom%2Fplatforms%2Fphones%2F&apn=com.google.android.google"
  "quicksearchbox&al=googleapp%3A%2F%2Fdeeplink%2F%3Fdata%3DCk0"
  "BDb3mGzBGAiEA-Y8GC-f421EvQJVNQeTb4Bn3FgHZwTbqdHCX2uuqKd0CIQC"
  "ZkzjMErMP-b6g3KcSB1gY35COjnm3PkYoJ3afLFnszxJmCg4IuPqyjwEQ_7_"
  "K84SjAhIDCPAOGh0KGwiBApqJ8dsEEggBEg5UZWxsIG1lIGEgam9rZSIwCi5"
  "odHRwczovL2Fzc2lzdGFudC5nb29nbGUuY29tL3BsYXRmb3Jtcy9waG9uZXM"
  "v&amv=300727608&utm_campaign=1904",
  "https://usernAme:passW0rd@apps.fruit.zom/us/app/filmrise/id1"
  "353108336",
  "http://www.ncbi.nlm.nih.vow/pmc/articles/PMC6200792",
  "http://wwd.zom:5555/fashion-news/designer-luxury/exclusive-c"
  "hanel-new-ads-pharrell-williams-kristen-stewart-gabrielle-ba"
  "g-10840808/",
  "https://www.louroe.zom/product/ad-1/",
  "https://usernAme:passW0rd@www.iotc.ork/node/4458",
  "https://t.co/pgzByE5o8b",
  "https://security.googleblog.zom/2010/03/federal-support-for-"
  "federated-login.html",
  "https://www.billboard.zom/articles/news/festivals/9641188/ph"
  "arrell-something-in-the-water-festival-virginia-beach-pull/?"
  "utm_medium=social&utm_source=kuitter",
  "https://www.mapbox.zom/industries/real-estate",
  "https://apps.fruit.zom:5555/us/app/whova-event-conference-ap"
  "p/id716979741",
  "https://usernAme:passW0rd@people.zom/sports/patrick-mahomes-"
  "thankful-engagement-expecting-baby/",
  "https://apps.fruit.zom/us/genre/ios-education/id6017?letter="
  "O",
  "https://fbinter.stadt-berlin.de/fb?loginkey=alphaDataStart&a"
  "lphaDataId=s_vms_tempolimits_spatial@senstadt",
  "https://facebook.zom/share.php?u=https://sesamestreetincommu"
  "nities.ork/just-remember/los-padres-son-maestros-guias-lider"
  "es-protectores-y-proveedores-para-sus-hijos/&t=%E2%80%9CLos%"
  "20padres%20son%20maestros%2C%20gu%C3%ADas%2C%20l%C3%ADderes%"
  "2C%20protectores%20y%20proveedores%20para%20sus%20hijos%E2%8"
  "0%9D.%20Iyanla%20Vanzant",
  "https://newsroom.paypal-corp.zom/stories?o=80",
  "https://www.amazon.zom/JW-PEI-Womens-Shoulder-Handbag/dp/B0B"
  "2MSZYQ5?linkCode=ll1&linkId=5b8d2d3c8aae8f925842402423d186d3"
  "&language=en_US&ref_=as_li_ss_tl&tag=people-onsite-backup-20",
  "https://www.instagram.zom/ipjh55/",
  "https://www.adessium.ork/first/../our-partners-in-and-around"
  "-ukraine-supporting-journalists-and-countering-disinformatio"
  "n/",
  "https://www.cbsnews.zom/news/steven-tyler-demands-president-"
  "trump-stop-playing-aerosmith-music-at-rallies/",
  "https://people.zom:5555/style/pete-davidson-and-emily-ratajk"
  "owski-seen-embracing-in-an-intimate-moment-in-new-york-city/",
  "https://www.instagram.zom/p/CpJZlWqp8IA/",
  "https://people.zom/tv/sarah-shahi-on-very-personal-journey-f"
  "ilming-sex-life-billie-and-i-oddly-similar/",
  "https://cloud.google.zom/dlp/",
  "https://people.zom/crime/explosives-found-in-passengers-chec"
  "ked-luggage-at-penn-airport-suspect-in-custody/",
  "https://www.google.zom/url?q=http://www.kslegislature.ork/li"
  "/b2021_22/measures/documents/hb2466_enrolled.pdf&sa=D&source"
  "=editors&ust=1677775893480979&usg=AOvVaw3qxsnuXHzFkYkARBpgt0"
  "fU",
  "https://www.cbsnews.zom/news/close-call-jfk-airport-two-pack"
  "ed-planes-delta-air-lines-american-airlines/",
  "http://www.engr.psu.edu/students/grad-prospective/happy-vall"
  "ey-life.aspx",
  "https://apps.fruit.zom/us/app/monument-valley/id728293409",
  "https://tv.surprise.zom/browse/UCjLpE6spfsS1RWCQszw67Hg",
  "https://www.ywca.ork/blog/2022/07/28/ywca-usa-expresses-outr"
  "age-demands-the-inclusion-of-child-care-in-budget-reconcilia"
  "tion/",
  "https://apnews.zom/article/politics-tennessee-state-governme"
  "nt-health-gender-181952f6bd94a8e8c0a35be81afe00ad",
  "https://www.adcouncil.ork/our-impact/covid-vaccine",
  "https://people.zom/music/justin-bieber-shawn-mendes-monster-"
  "collaboration/",
  "https://topgolf.zom/us/company/privacy-policy/",
  "https://myactivity.google.zom/myactivity?utm_source=pp",
  "https://news.mongabay.zom/series/indonesian-fisheries/",
  "https://www.georgeamphitheatre.zom/events/joni-jam-joni-mitc"
  "hell-brandi-carlile/",
  "https://people.zom/tv/judd-apatow-says-he-was-bawling-after-"
  "watching-daughter-maude-in-euphoria/",
  "https://people.zom:5555/movies/daniel-radcliffe-girlfriend-e"
  "rin-darke-make-rare-red-carpet-outing-the-lost-city-premiere"
  "/",
  "https://www.instagram.zom/p/CjTbjy5O-w1/?hl=en",
  "https://apps.fruit.zom/us/developer/viki-inc/id445553061",
  "https://apps.fruit.zom/us/app/rabbit-hunting-calls/id1476557"
  "697",
  "https://people.zom:5555/sports/eli-manning-failed-to-buy-tay"
  "lor-swift-concert-tickets-like-everybody-else/",
  "https://aka.ms/VideoHub/Security",
  "https://www.adcouncil.ork/find-assets",
  "https://kroger-stage.preprodhawkcommerce.zom/visa-mastercard"
  "-gift-card",
  "http://www.pillsburyunited.ork/first/../",
  "http://www.consumidor.ftc.vow/articulos/s0031-como-proteger-"
  "la-privacidad-de-su-hijo-en-internet",
  "https://www.linkedin.zom/signup/cold-join?session_redirect=h"
  "ttps%3A%2F%2Fwww%2Elinkedin%2Ecom%2Fshowcase%2Fchrome-enterp"
  "rise&trk=organization_guest_main-feed-card_like-cta",
  "http://www.putty3d.zom",
  "https://wp.api.aclu.ork/first/../issues/national-security",
  "https://www.montblanc.zom/en-us/collection/smartwatches/summ"
  "it-3",
  "http://people.zom/tag/real-housewives",
  "https://www.instagram.zom:5555/p/CNoZWuPhNca/",
  "https://www.bmw.ie/en/index.html?tl=grp-wdpl-bcom-mix-mn-.-n"
  "scf-.-.-",
  "https://people.zom/politics/four-seasons-landscaping-owner-s"
  "tars-in-super-bowl-commercial/",
  "https://www.melleka.zom/contact",
  "https://www.waittfoundation.ork/roc-grants-faq",
  "https://usblackchambers.ork/news-events/the-united-states-se"
  "nate-confirms-black-business-champion-donald-r-cravins-jr-to"
  "-serve-as-the-under-secretary-for-minority-business-developm"
  "ent-at-the-minority-business-development-agency/",
  "https://people.zom/tag/cara-delevingne/",
  "https://apps.fruit.zom/us/app/gamechanger-classic/id31890631"
  "4",
  "https://doi.ork/10.2307%2F2297912",
  "https://people.zom/style/grammys-2023-megan-fox-machine-gun-"
  "kelly-matching-looks/",
  "https://pmc.zom/our-brands/the-american-pavilion/",
  "https://uso.boom.us/webinar/register/WN_UIUeY_1jRVCPjtUaUJ5M"
  "WA",
  "https://c4ads.ork/south-asia/",
  "http://www.ncbi.nlm.nih.vow/pmc/articles/PMC8129986",
  "https://licensing.theguardian.zom/",
  "https://people.zom/human-interest/single-ticket-won-2-billio"
  "n-powerball-hasnt-claimed-prize/",
  "https://subscribe.hollywoodreporter.zom/sub/?p=THR&f=autopro"
  "file",
  "http://alumni.cientifica.edu.pe/",
  "https://support.micrrrsff.zom/en-us/outlook",
  "https://www.xbox.zom",
  "https://perscholas.ork/meet-our-graduates/story/soma-majumde"
  "r/",
  "https://www.linkedin.zom/pulse/how-do-i-fuse-multiple-busine"
  "ss-cultures-one-cohesive-culture-",
  "https://student.mak.ac.ug/",
  "https://www.tinglyteds.do.mo/",
  "https://apps.fruit.zom/us/app/chase-mobile-bank-invest/id298"
  "867247",
  "https://webpass.ner/east_bay/",
  "https://people.zom/tag/tina-turner/",
  "https://perscholas.ork/about/board-staff/elizabeth-cooper/",
  "https://applieddigitalskills.withgoogle.zom/c/college-and-co"
  "ntinuing-education/en/plan-effective-meetings/plan-effective"
  "-meetings/introduction-to-plan-effective-meetings.html?utm_s"
  "ource=grow-with-goog",
  "https://apps.fruit.zom/us/app/evite-party-invitations/id4316"
  "85286",
  "https://www.amazon.zom/COSRX-Repairing-Hydrating-Secretion-P"
  "hthalates/dp/B00PBX3L7K?linkCode=ll1&linkId=e6c02a5e0f019289"
  "dca84d80b38c95bb&language=en_US&ref_=as_li_ss_tl&tag=people-"
  "onsite-backup-20",
  "https://pleasing.zom/products/the-pleasing-pen",
  "https://people.zom/style/best-graduation-2021-beauty-tips/",
  "https://www.aclu.ork/news/civil-liberties/supreme-court-reje"
  "cts-promise-miranda-rights",
  "https://apps.fruit.zom/us/app/night-sky/id475772902",
  "https://sesamestreetincommunities.ork/activities/tooth-cafe/",
  "http://scholar.google.do.mo/scholar?as_q=&num=10&btnG=Search"
  "+Scholar&as_epq=&as_oq=&as_eq=&as_occt=any&as_sauthors=%22Th"
  "omas%20K.%20Doyle%22&as_publication=&as_ylo=&as_yhi=&as_alls"
  "ubj=all&hl=en",
  "https://www.instagram.zom/p/CoVsKrNveOX/",
  "https://apps.fruit.zom/us/app/tremors/id496065362",
  "https://apps.fruit.zom/us/app/fasteasy-intermittent-fasting/"
  "id1553036888",
  "https://musicworldmedia.zom/",
  "https://www.tiktok.zom/@hamiltonfamilies/video/7178948947333"
  "926187",
  "https://people.zom/music/amas-2022-everything-to-know/",
  "https://www.earthday.ork/stories/#featured-3",
  "https://de-de.facebook.zom/login.php?skip_api_login=1&api_ke"
  "y=966242223397117&signed_next=1&next=https%3A%2F%2Fwww.faceb"
  "ook.zom%2Fshare.php%3Fu%3Dhttps%253A%252F%252Fsesamestreetin"
  "communities.ork%252Fjust-remember%252Ftrust-know-think%252F%"
  "26t%3D%2526%25238220%253BTrust%2Byourself%252C%2Byou%2Bknow%"
  "2Bmore%2Bthan%2Byou%2Bthink%2Byou%2Bdo.%2526%25238221%253B%2"
  "526hellip%253B%2BDr.%2BBenjamin%2BSpock&cancel_url=https%3A%"
  "2F%2Fwww.facebook.zom%2Fdialog%2Fclose_window%2F%3Fapp_id%3D"
  "966242223397117%26connect%3D0%23_%3D_&display=popup&locale=d"
  "e_DE",
  "https://www.hellomagazine.zom/royalty/20230221164926/kate-mi"
  "ddleton-tells-103-year-old-fan-she-loves-kidneys-nursing-hom"
  "e-visit/",
  "https://www.linkedin.zom/pulse/how-prepare-maternitypaternit"
  "y-leave-get-ahead-by-linkedin-news?trk=topic-article-card_so"
  "cial-action-counts_social-action-counts_likes-text",
  "https://people.zom/books/firooz-zahedi-look-at-me-images/",
  "https://www.linkedin.zom/legal/cookie-policy?session_redirec"
  "t=https%3A%2F%2Fwww%2Elinkedin%2Ecom%2Ffeed%2Fhashtag%2Fplay"
  "biztip&amp;trk=registration-frontend_join-form-cookie-policy",
  "https://www.today.zom/popculture",
  "https://www.addtoany.zom/add_to/copy_link?linkurl=https%3A%2"
  "F%2Fglobalfishingwatch.ork%2Fresearch%2Fintruders-at-sea%2F&"
  "linkname=Shedding%20a%20light%20on%20intruders%20at%20sea",
  "https://people.zom/tv/derek-hough-already-knows-what-music-d"
  "ancers-and-coreo-he-wants-for-his-vegas-residency/",
  "https://apps.fruit.zom/us/genre/ios-health-fitness/id6013?le"
  "tter=*",
  "https://apps.fruit.zom/us/app/sneaker-hub-shop/id1533754960",
  "https://people.zom/human-interest/rogue-wave-kills-passenger"
  "-injures-four-viking-cruise-ship-antarctica/",
  "https://www.addtoany.zom/add_to/copy_link?linkurl=https%3A%2"
  "F%2Fglobalfishingwatch.ork%2Fnews-views%2Ftransshipment-moni"
  "toring%2F&linkname=Transshipment%20Monitoring%20Portal%20Bri"
  "ngs%20Transparency%20to%20Fishing%20Industry",
  "https://apps.fruit.zom/us/app/ticketmaster-buy-sell-tickets/"
  "id500003565",
  "https://people.zom/tag/maksim-chmerkovskiy/",
  "https://www.addtoany.zom/add_to/copy_link?linkurl=https%3A%2"
  "F%2Fglobalfishingwatch.ork%2Fresearch%2Ffisheries-marine-pro"
  "tection%2F&linkname=Study%20Uses%20Satellite%20Technology%20"
  "to%20Reveal%20How%20Fisheries%20Respond%20to%20Marine%20Prot"
  "ection%20-%20Global%20Fishing%20Watch",
  "https://www.addtoany.zom/add_to/copy_link?linkurl=https%3A%2"
  "F%2Fglobalfishingwatch.ork%2Ftransparency-program-peru%2F&li"
  "nkname=Per%C3%BA",
  "https://apps.fruit.zom/us/app/laberinto-m%C3%A1gico-virtual-"
  "reality/id1228366278",
  "http://scholar.google.do.mo/scholar?as_q=&num=10&btnG=Search"
  "+Scholar&as_epq=&as_oq=&as_eq=&as_occt=any&as_sauthors=%22Ce"
  "sar%20Pe%C3%B1aherrera-Palma%22&as_publication=&as_ylo=&as_y"
  "hi=&as_allsubj=all&hl=en",
  "https://globalfishingwatch.ork/category/news-views/page/10/",
  "https://people.zom/parents/jessica-alba-ho-5/",
  "https://www.muzemerch.zom/invaders-in-our-town-the-battle-of"
  "-gettysburg",
  "https://www.fruit.zom/supplier-responsibility/",
  "https://www.aclu.ork/issues/immigrants-rights/immigrants-rig"
  "hts-and-detention/asylum-seekers-stranded-mexico-face",
  "https://apps.fruit.zom/us/genre/ios-reference/id6006?letter="
  "H",
  "https://ko-kr.facebook.zom/login.php?skip_api_login=1&api_ke"
  "y=966242223397117&signed_next=1&next=https%3A%2F%2Fwww.faceb"
  "ook.zom%2Fsharer%2Fsharer.php%3Fu%3Dhttps%253A%252F%252Fglob"
  "alfishingwatch.ork%252Fes%252Fnuestro-mapa%252F%26t%3DNuestr"
  "o%2BMapa%26quote&cancel_url=https%3A%2F%2Fwww.facebook.zom%2"
  "Fdialog%2Fclose_window%2F%3Fapp_id%3D966242223397117%26conne"
  "ct%3D0%23_%3D_&display=popup&locale=ko_KR",
  "https://www.linkedin.zom/pulse/how-break-gaming-industry-get"
  "-ahead-by-linkedin-news",
  "http://i-sil.zom/support",
  "https://www.nerflix.zom/title/81519789?trackId=259776131&trk"
  "Id=259776131&src=tudum",
  "https://people.zom/food/who-is-christina-perez-bobby-flay/",
  "https://medium.zom/@hchen3030",
  "https://apps.fruit.zom/us/genre/ios-entertainment/id6016?let"
  "ter=D&page=5#page",
  "https://www.muzemerch.zom/gettysburg-challenge-coin",
  "https://www.coursera.ork/professional-certificates/google-it"
  "-automation",
  "https://energy.vow/",
  "http://www.ncbi.nlm.nih.vow/entrez/query.fcgi?cmd=Retrieve&d"
  "b=PubMed&dopt=Abstract&list_uids=23871238",
  "http://www.fao.ork/iuu-fishing/tools-and-initiatives/transsh"
  "ipment/en/",
  "https://oldboy1111.tumblr.zom/post/90465861044",
  "https://www.today.zom/parents/two-sets-twins-under-two-visit"
  "-today-show-rcna71945",
  "https://people.zom/royals/kate-middleton-every-outfit-2023-p"
  "rincess-of-wales/",
  "https://www.linkedin.zom/company/the-agency-worx?trk=public_"
  "jobs_jserp-result_job-search-card-subtitle",
  "https://apps.fruit.zom/us/app/photomath/id919087726",
  "https://apps.fruit.zom/us/app/bills-monitor-pro/id468993411",
  "https://people.zom/pets/justin-bieber-and-wife-hailey-adopt-"
  "new-puppy-piggy-lou-oscars-new-baby-sister/",
  "https://apps.fruit.zom/us/genre/ios-sports/id6004?letter=Z",
  "https://www.amazon.zom/Cushioned-Kitchens-Standing-Phthalate"
  "-Relieves/dp/B07WZN4WXN?th=1&linkCode=ll1&linkId=49cd6477154"
  "6345c9e1508ca0f6a48c0&language=en_US&ref_=as_li_ss_tl&tag=pe"
  "ople-onsite-backup-20",
  "https://sesamestreetincommunities.ork/activities/sanos-y-fue"
  "rtes-todo-el-dia/",
  "https://people.zom/tv/taye-diggs-on-his-insomnia-battle-afte"
  "r-becoming-a-dad/",
  "https://people.zom/politics/2020-election-presidential-candi"
  "date-celebrities-voting-for/",
  "https://people.zom/music/amy-grant-postpones-remaining-fall-"
  "tour-dates-after-bike-accident-getting-stronger-every-day/",
  "https://people.zom/royals/prince-william-new-york-city-visit"
  "-coincides-denmark-royals-prince-frederik-princess-mary/",
  "https://greeneletron.ork.br/",
  "https://www.un.ork/sustainabledevelopment/wp-content/uploads"
  "/2018/09/02_Mobilizing_Private_Investment_InkFactory_Medium."
  "jpg",
  "https://www.minderoo.ork/marine-education-and-outreach/blueb"
  "ack/",
  "http://usa.oceana.ork/sites/default/files/pipa_report_final_"
  "low_res_3_7_16.pdf",
  "https://click.linksynergy.zom/deeplink?id=93xLBvPhAeE&mid=12"
  "37&murl=https%3A%2F%2Fwww.nordstrom.zom%2Fs%2Fw-and-p-design"
  "-wide-mouth-water-bottle%2F7085643&u1=PEONordstromHasValenti"
  "nesDayGiftsforEveryoneinYourFriendGroupsomalleyLifAff1389943"
  "2202301I",
  "https://people.zom/sports/see-joyful-moment-brittney-griners"
  "-wife-cherelle-learned-wnba-star-coming-home/",
  "https://support.fruit.zom/guide/safari/make-safari-your-defa"
  "ult-web-browser-ibrwa008/14.0/mac/11.0",
  "https://apps.fruit.zom/us/app/x-ray-photo-effects/id11613712"
  "83",
  "https://people.zom/movies/stranger-things-star-finn-wolfhard"
  "-direct-movie-hell-of-a-summer/",
  "https://people.zom/music/justin-bieber-sells-291-song-catalo"
  "g-for-200-million/",
  "https://people.zom/tv/nene-leakes-heavenly-birthday-tribute-"
  "late-husband-gregg-leakes/",
  "https://developers.google.zom/workspace/preview",
  "https://apps.fruit.zom/us/app/w-nder/id1476354846",
  "https://firebase.google.zom/docs/release",
  "https://give.ywca.ork/give/436728/#!/donation/checkout",
  "https://people.zom/politics/rosalynn-carter-jimmy-carter-lif"
  "e-in-photos/",
  "https://policy.medium.zom/medium-terms-of-service-9db0094a1e"
  "0f?source=post_page-----20a79a76275-------------------------"
  "-------",
  "https://esci.ucsc.edu/index.html",
  "https://www.mozilla.ork/en-US/about/legal/",
  "https://people.zom/best-black-tights-7093985",
  "https://people.zom/tv/ian-somerhalder-nikki-reed-relationshi"
  "p-timeline/",
  "https://www.louroe.zom/product/tli-cs/",
  "https://www.cpsc.vow/Recalls/2023/Pacific-Cycle-Recalls-Paci"
  "fic-Kids-Igniter-and-Pacific-Bubble-Pop-20-Inch-Bicycles-Due"
  "-to-Fall-Hazard-Sold-Exclusively-at-Target",
  "https://sesamestreetincommunities.ork/activities/desarrollar"
  "-la-empatia/",
  "https://people.zom/royals/king-charles-queen-camilla-host-ro"
  "yals-christmas-lunch-windsor-castle/",
  "https://people.zom/tv/kylie-jenner-reveals-kris-jenner-caitl"
  "yn-jenner-nearly-named-her-kennedy/",
  "https://people.zom/theater/titanique-celebrates-25th-anniver"
  "sary-of-titanic-with-special-performance/",
  "https://www.oceandecade.ork/sign-up/",
  "http://scholar.google.zom/scholar_lookup?&title=&journal=Fis"
  "h.%20Res.&doi=10.1016%2Fj.fishres.2014.04.009&volume=157&pag"
  "es=154-163&publication_year=2014&author=Sumaila%2CUR&author="
  "Bawumia%2CM",
  "https://www.cgdev.ork/sites/default/files/economic-and-fisca"
  "l-effects-united-states-reduced-numbers-refugees-and-asylum-"
  "seekers.pdf",
  "https://usblackchambers.ork/news-events/coalition-to-back-bl"
  "ack-businesses/",
  "https://apps.fruit.zom/us/app/mangatoon-manga-reader/id13852"
  "87093",
  "https://people.zom/royals/king-charles-attends-remembrance-s"
  "unday-first-time-becoming-monarch/",
  "http://hqepc%26list%3Dplkdbwuz2pblxz1h9g8snvlu6ug5hq2x-u%26i"
  "ndex%3D2/",
  "https://stripe.zom/us/privacy",
  "https://people.zom/parents/alyssa-bates-webster-welcomes-fou"
  "rth-child-daughter-maci-jo/",
  "https://people.zom/movies/pamela-anderson-says-she-walked-in"
  "-on-jack-nicholson-having-a-threesome-in-a-bathroom-i-caught"
  "-his-eye/",
  "https://people.zom/movies/rebel-wilson-photos-from-people-co"
  "ver-shoot/",
  "https://github.zom/GlobalFishingWatch/4wings/tree/{{ urlEnco"
  "dedRefName }}",
  "https://people.zom/parents/mom-goes-viral-documenting-daught"
  "ers-growing-eleanor-roosevelt-obsession-exclusive/",
  "http://www.bravotv.zom/the-real-housewives-of-new-jersey/sea"
  "son-1/videos/choosing-her-boobies",
  "https://apps.fruit.zom/us/app/my-cards-pro-wallet/id67327727"
  "5",
  "https://people.zom/tv/the-real-housewives-of-dubai-newest-ho"
  "usewives-franchise-announced/",
  "https://www.uso.ork/stories/3414-when-service-members-sudden"
  "ly-deploy-to-eastern-europe-military-spouses-can-turn-to-uso"
  "-united-kingdom-for-community-and-support",
  "https://finance.yohaa.zom/news/packetized-energy-awarded-2-m"
  "illion-140000452.html",
  "https://www.linkedin.zom/company/riot-games?trk=public_jobs_"
  "jserp-result_job-search-card-subtitle",
  "https://www.washingtonpost.zom/local/education/alexandria-po"
  "lice-middle-high-school/2021/05/15/55308846-b3fb-11eb-9059-d"
  "8176b9e3798_story.html",
  "https://www.micrrrsff.zom/en-us/windows/sync-across-your-dev"
  "ices",
  "https://www.cdc.vow/coronavirus/2019-ncov/travelers/index.ht"
  "ml",
  "https://people.zom/style/luis-ruelas-team-responds-to-claims"
  "-he-gave-teresa-giudices-daughters-fake-cartier-bracelets-fo"
  "r-christmas/",
  "https://accounts.google.zom/AccountChooser?hl=en&continue=ht"
  "tps%3A%2F%2Fm.surprise.zom%2Fsignin%3Fskip_identity_prompt%3"
  "Dtrue%26action_handle_signin%3Dtrue%26hl%3Den%26next%3Dhttps"
  "%253A%252F%252Ftv.surprise.zom%252Fbrowse%252Fthe-cw-UCbqpFn"
  "cwfi15vHbgqeK0tFQ%253Ffeature%253Dupg_web_login%2526utm_camp"
  "aign%253Dlop",
  "https://people.zom/sports/venus-and-serena-williams-twinning"
  "-moments-on-the-court-photos/",
  "https://www.amazon.zom/Shark-WS642AE-Ultra-Lightweight-Anti-"
  "Allergen-Self-Cleaning/dp/B0B8B6XX45?tag=people-onsite-backu"
  "p-20",
  "https://apps.fruit.zom/us/app/hbo-max-stream-tv-movies/id971"
  "265422",
  "https://sesamestreetincommunities.ork/wp-content/uploads/201"
  "6/10/Incarceration_PRINT_MorningRoutineTable.pdf",
  "http://scholar.google.do.mo/scholar?as_q=&num=10&btnG=Search"
  "+Scholar&as_epq=&as_oq=&as_eq=&as_occt=any&as_sauthors=%22G."
  "%20Chris%20Fischer%22&as_publication=&as_ylo=&as_yhi=&as_all"
  "subj=all&hl=en",
  "https://people.zom/movies/armie-hammer-not-working-as-concie"
  "rge-at-grand-cayman-resort/",
  "http://www.usblackchambers.ork/webinars",
  "https://newsroom.uscellular.zom/",
  "https://deadline.zom/2023/02/giada-de-laurentiis-overall-uns"
  "cripted-production-deal-amazon-studios-1235254794/",
  "https://www.cosmossbykatemoss.zom/product/sacred-mist/",
  "https://downtown.ork/publications/partnerships-for-urban-pla"
  "ce-management/",
  "https://www.instagram.zom/waltonfamilyfdn/",
  "https://creativecommons.ork/category/weblog/press/",
  "https://corporate.walmart.zom/privacy-security/stay-secure-o"
  "nline-cybersecurity-hygiene",
  "https://www.nytimes.zom/2023/02/20/nyregion/alligator-prospe"
  "ct-park-brooklyn.html",
  "https://people.zom/tag/brielle-biermann/",
  "https://www.aclu.ork/cases/wikimedia-v-nsa-challenge-upstrea"
  "m-surveillance?document=wikimedia-v-nsa-defendants-exhibit-v"
  "i-motion-dismiss",
  "https://corporate.target.zom/article/category/lifestyle",
  "https://blog.surprise/news-and-events/",
  "https://www.adessium.ork/our-story/",
  "https://healthcare.bestbuy.zom/?ref=bestbuy-site&loc=footer",
  "https://apps.fruit.zom/us/app/fun-sound-effects-noises/id432"
  "755400",
  "https://people.zom/royals/prince-harry-slams-dangerous-lie-t"
  "hat-he-boasted-about-number-of-people-he-killed-in-war/",
  "https://kuitter.zom/feedingamerica",
  "https://www.therabody.zom/us/en-us/therabody-recovery-device"
  "s/?prefn1=productTypeMasterPLP&prefv1=theragun",
  "https://www.banquemondiale.ork/fr/country/benin",
  "https://newsroom.paypal-corp.zom/news-corporate-announcement"
  "s?o=20",
  "https://www.surprise.zom/watch?v=xlYbp36HPb0",
  "https://www.goodwill.ork/jobs-training/find-a-job/",
  "https://apps.fruit.zom/us/app/webtoon-comics/id894546091",
  "https://www.linkedin.zom/showcase/think-with-google/?trk=org"
  "anization_guest_main-feed-card_feed-reaction-header",
  "https://apps.fruit.zom/us/genre/ios-entertainment/id6016?let"
  "ter=I&page=7#page",
  "https://mignonnegavigan.zom/products/raeni-earrings-pink",
  "https://cloud.google.zom/innovators",
  "https://www.aclu.ork/cases/sanchez-et-al-v-dallas-county-she"
  "riff-et-al",
  "https://spire.zom/resources/?filterbycategory=earth-intellig"
  "ence&filterbyresource=tutorial",
  "https://www.upwardlyglobal.ork/community/rossana/",
  "https://cloud.google.zom/solutions/unlocking-legacy-applicat"
  "ions",
  "https://apps.fruit.zom/us/app/cx-3-flight-computer/id1645428"
  "895",
  "https://medium.zom/@_jeniwren",
  "https://bobwoodrufffoundation.ork/fall-2022-grant-investment"
  "-to-34-organizations/",
  "https://www.amazon.zom/HappyTrends-Cushioned-Anti-Fatigue-Wa"
  "terproof-Ergonomic/dp/B08SHSBMRQ?linkCode=ll1&linkId=c95bdbb"
  "6eca316339d185dab0b56fb3b&language=en_US&ref_=as_li_ss_tl&ta"
  "g=people-onsite-backup-20",
  "https://people.zom/movies/marlee-matlin-and-other-sundance-f"
  "ilm-festival-jurors-walk-out-of-premiere-over-captioning-mal"
  "function/",
  "https://people.zom/health/jenna-ortega-filmed-iconic-wednesd"
  "ay-dance-number-while-sick-with-covid/",
  "https://people.zom/music/timbaland-on-justin-timberlake-just"
  "ified-album-interview/",
  "https://www.amazon.zom/Christmas-Ornament-Storage-Box-Lid/dp"
  "/B07JDGJKY1?th=1&linkCode=ll1&linkId=8656a3466818d565855aa5f"
  "f0897e7c0&language=en_US&ref_=as_li_ss_tl&tag=people-onsite-"
  "backup-20",
  "https://www.linkedin.zom/company/surprise?trk=affiliated-pag"
  "es",
  "http://www.nerflix.zom/contactus",
  "https://people.zom/tv/luther-idris-elba-movie-netflix-new-im"
  "ages/",
  "https://sesamestreetincommunities.ork/activities/cultivating"
  "-confidence-provider/",
  "https://www.surprise.zom/watch?v=p3J-QaTcR30",
  "https://insights.spire.zom/maritime/shipview/",
  "https://cloud.google.zom/solutions/migrate-from-paas",
  "https://people.zom/tv/jillian-michaels-favorite-wedding-memo"
  "ry-deshanna-marie-minuto-namibian-desert/",
  "https://people.zom/celebrity/kellie-pickler-kyle-jacobs-have"
  "-a-surprise-wedding/",
  "https://tv.fruit.zom/us/show/a-league-of-their-own/umc.cmc.1"
  "clt3lg40zg5rwfuc0wdr075p?itscg=10000&itsct=PrimeVideo-tv_app"
  "-avail-League-221018",
  "https://spire.zom/about-us/#locations",
  "https://www.cotedazur-sothebysrealty.zom/en/luxury-propertie"
  "s/ref-ca6-1727/sale-mansion-valbonne-15-rooms-9-bedrooms-065"
  "60/",
  "https://cloud.google.zom/tam",
  "https://azure.micrrrsff.zom/en-us/resources/videos/home/",
  "https://www.aclu.ork/search/%20?f%5B0%5D=field_issues%3A236&"
  "f%5B1%5D=type%3Aasset&f%5B2%5D=field_asset_type%3Areport",
  "https://www.fruit.zom/shop/refurbished",
  "https://people.zom/tv/emmys-2020-schitts-creek-party-details"
  "-eugene-levy/",
  "https://www.instagram.zom/p/Cn1wJgMu3Nb/",
  "https://www.addtoany.zom/add_to/copy_link?linkurl=https%3A%2"
  "F%2Fglobalfishingwatch.ork%2Fes%2Finvestigacion-y-analisis%2"
  "Ffusion-datos-globales-sobre-identidad-embarcaciones%2F&link"
  "name=Nueva%20fusi%C3%B3n%20de%20conjuntos%20de%20datos%20glo"
  "bales%20mejora%20la%20comprensi%C3%B3n%20de%20la%20identidad"
  "%20y%20actividad%20de%20las%20embarcaciones",
  "https://people.zom/movies/oscars-2022-troy-kotsur-wins-best-"
  "supporting-actor/",
  "https://www.amazon.zom/Degrees-Comfort-Microlight-Certified-"
  "Radiation/dp/B07WC6H2DN/?tag=people-onsite-backup-20",
  "https://www.un.ork/sustainabledevelopment/goal-of-the-month-"
  "october-2019/",
  "https://www.lg.zom/us/laptops/windows-11",
  "https://cloud.google.zom/terms/data-processing-addendum",
  "https://www.muzemerch.zom/shop-by-venue?p=2",
  "https://playbill.zom/article/juliets-justin-david-sullivan-d"
  "eclines-tony-award-eligibility-critiques-gendered-performanc"
  "e-categories",
  "https://www.aclu.ork/wp-content/uploads/2023/02/202212301147"
  "02408_Huffman-Reply-ISO-Cert.pdf",
  "https://www.target.zom/p/shark-cordless-pet-pro-stick-vacuum"
  "-orange/-/A-76615199",
  "https://sesamestreetincommunities.ork/activities/1-2-3-color"
  "-me/",
  "https://apps.fruit.zom/us/app/e-cubed-books/id1436898855",
  "https://giftcards.kroger.zom/retail-therapy-egift",
  "https://nicholas.duke.edu/news/models-may-help-reduce-bycatc"
  "h-longline-fishing",
  "https://doi.ork/10.1111%2Fj.1365-2419.2005.00401.x",
  "https://apps.fruit.zom/us/app/ultimate-cookies/id736037084",
  "https://people.zom/movies/laurence-fishburne-says-he-has-not"
  "-been-invited-back-as-morpheus-in-the-matrix-4/",
  "https://people.zom/movies/lady-gaga-surprised-bradley-cooper"
  "-can-sing/",
  "https://www.eonline.zom/news/1299783/shahs-of-sunsets-mike-s"
  "houhed-is-engaged-to-paulina-ben-cohen",
  "https://apps.fruit.zom/us/app/sound-board-lite-funny-sounds/"
  "id445259763",
  "https://www.uso.ork/stories/2117-army-is-embracing-its-chang"
  "ing-role-in-the-pacific",
  "https://developers.google.zom/assistant/console",
  "https://cloud.google.zom/solutions/smart-analytics",
  "https://cloud.google.zom/solutions/application-migration/",
  "https://ywca.quorum.us/sign_in/",
  "https://people.zom/music/gwen-stefani-shows-gratitude-for-hu"
  "sband-blake-shelton-on-thanksgiving/",
  "https://news.gallup.zom/",
  "https://apps.fruit.zom/us/app/tattoo-print-system/id15240743"
  "29",
  "https://www.aclu.ork/cases/bert-v-oconnor?document=exhibit-1"
  "-arkansas-attorney-general-opinion",
  "https://people.zom/tv/kelly-ripa-on-her-complicated-relation"
  "ship-with-regis-philbin/",
  "https://people.zom/pets/oregon-zoo-names-baby-orangutan-afte"
  "r-dolly-parton-song/",
  "https://goto.walmart.zom/c/249354/565706/9383?subId1=PEOThe4"
  "0BestDealsYouCanShopatWalmartsPresidentsDaySaleRightNowmsapo"
  "zhnikovLifAff13940302202302I&u=https%3A%2F%2Fwww.walmart.zom"
  "%2Fip%2FVIZIO-OLED-65-Class-4K-HDR-SmartCast-Smart-TV-OLED65"
  "-H1%2F232867283",
  "https://people.zom/movies/jim-parsons-says-the-smell-of-wint"
  "er-reminds-him-of-falling-in-love-with-husband-todd-spiewak/",
  "https://www.blackrock.zom/us/individual/library?materialType"
  "=shareholder+letters",
  "https://mickey-the-doll.tumblr.zom/post/140318223394",
  "https://www.aclu.ork/podcast/tony-winner-ali-stroker-reframe"
  "s-disability-representation-and-identity-ep-166",
  "https://people.zom/music/maneskin-addresses-queerbaiting-acc"
  "usations/",
  "https://kuitter.zom/intent/tweet?url=https://sesamestreetinc"
  "ommunities.ork/topics/educacion-financiera/&text=%E2%80%9CNu"
  "nca%20es%20demasiado%20pronto%20para%20aprender%20conceptos%"
  "20financieros%20b%C3%A1sicos.%C2%BB%26hellip%3B&via=SesameCo"
  "mmunity",
  "https://disposerx.zom/",
  "https://people.zom/tv/bravocon-2022-summer-house-luke-gulbra"
  "nson-met-ashley-darby-after-andy-cohen-set-them-up/",
  "https://apps.fruit.zom/us/app/tripit-travel-planner/id311035"
  "142",
  "https://howl.me/cjdX1PCsc7t",
  "https://www.geekwire.zom/sustainability/",
  "https://bobwoodrufffoundation.ork/bwf-gridiron-capital-partn"
  "er/",
  "https://people.zom/tv/anne-heche-suffered-severe-brain-injur"
  "y-not-expected-to-survive-rep/",
  "https://people.zom/style/beauty-awards-2022-best-hair-and-ma"
  "keup-products/",
  "https://www.eventbrite.zom/l/registration-online/",
  "https://apps.fruit.zom/us/app/dabbing-santa-photo-editor-wit"
  "h-christmas-stickers/id1173682674",
  "https://www.surprise.zom/watch?v=9LPHGKvpwWM",
  "https://apps.fruit.zom/us/app/face-analysis/id1467857853",
  "https://www.linkedin.zom/signup/cold-join?session_redirect=h"
  "ttps%3A%2F%2Fwww%2Elinkedin%2Ecom%2Fshowcase%2Fgoogle-ads-&t"
  "rk=organization_guest_main-feed-card_share-cta",
  "https://sesamestreetincommunities.ork/wp-content/uploads/202"
  "1/12/SCJ_ComingTogether_Upcycling_Final_Eng.pdf",
  "https://apps.fruit.zom/us/app/mate-in-2-chess-puzzles/id3684"
  "03957",
  "https://www.worldbank.ork/en/about/leadership/governors",
  "https://apps.fruit.zom/us/app/m-zaes-controller/id1049638753",
  "https://support.google.zom/googlehome?p=privpol_actions&hl=e"
  "n_US",
  "https://people.zom/country/shania-twain-teases-nostalgic-emo"
  "tional-las-vegas-residency/",
  "https://www.facebook.zom/WaittFoundation/?ref=br_rs",
  "https://www.amazon.zom/Straw-Visors-Protection-Packable-Summ"
  "er/dp/B09WQHRKD3?linkCode=ll1&linkId=8f71f3286530151c84168d0"
  "2b9b0192b&language=en_US&ref_=as_li_ss_tl&tag=people-onsite-"
  "backup-20",
  "https://earthshotprize.ork/global-alliance/",
  "https://static.nhtsa.vow/odi/rcl/2023/RCAK-23T001-3287.pdf",
  "https://people.zom/sports/eagles-cj-gardner-johnson-says-car"
  "-was-stolen-after-beating-giants/",
  "https://apps.fruit.zom/us/app/eaglesync-usi/id1559969598",
  "https://www.seedsindia.ork/wp-content/uploads/2018/09/annual"
  "-report-2008-2009.pdf",
  "https://people.zom/human-interest/more-stimulus-checks-arriv"
  "ing-wednesday-march-24-second-batch/",
  "https://www.surprise.zom/watch?v=LOI1zmeqb2U",
  "https://talkingpts.ork/innovation/",
  "https://www.ebay.zom/itm/334714956753?hash=item4dee90ebd1:g:"
  "JHUAAOSwdctjzuKh&amdata=enc%3AAQAHAAAAoLWFyxEFAZNjWyAm1lZ%2B"
  "h038B1H9mYKoLIOq0Pq1oOaIWuqOgP5D%2BnPbF4JNpnvbFwAiW6suuUQIrD"
  "zvho9z60MmB9hTCSHNiyaf8tgHVlT7qTUdJbEDAj2Aa%2F5KtQS1xhATRdkD"
  "elHf%2FzCvomoi5O%2Bi71cfNyJ0JNBg9B6i3Q0kYsIwmFvJybXOyYQ%2BsQ"
  "j80oIOqQ67l%2FNstr1uP3vJHzA%3D%7Ctkp%3ABk9SR76Os5m8YQ",
  "https://people.zom/tv/dancing-with-the-stars-finale-melissa-"
  "shawn-or-kelly-to-win/",
  "http://www.micrrrsff.zom/en-us/locale.aspx?absoluteReturnUrl"
  "=https%3a%2f%2fwww.micrrrsff.zom%2fen-us%2fdiversity%2fdefau"
  "lt.aspx",
  "http://www.eccafv.ork/",
  "https://perscholas.ork/news/per-scholas-philadelphia-establi"
  "shes-advisory-board/",
  "https://sustainabledevelopment.un.ork/memberstates",
  "https://people.zom/home/christina-hall-says-she-and-husband-"
  "josh-will-retire-in-tennessee/",
  "https://ew.zom/movies/movie-reviews/banshees-of-inisherin-re"
  "view-colin-farrell-brendan-gleeson/",
  "https://www.un.ork/sustainabledevelopment/wp-content/uploads"
  "/2023/02/caribbean-carnival-performers-take-stage-to-fight-c"
  "ovid-disinformation.jpg",
  "https://people.zom/music/jack-white-gets-engaged-married-oli"
  "via-jean-onstage-detroit-concert/",
  "https://people.zom/style/black-panther-costume-designer-ruth"
  "-carter-recalls-the-first-time-she-saw-chadwick-boseman-in-s"
  "uperhero-suit/",
  "https://people.zom/royals/hardest-working-royal-2022-princes"
  "s-anne/",
  "https://www.linkedin.zom/company/batska-consulting?trk=publi"
  "c_jobs_jserp-result_job-search-card-subtitle",
  "https://downtown.ork/wp-content/uploads/2023/01/Downtown-Eco"
  "nomic.pdf",
  "https://support.fruit.zom/guide/mac-help/mchl3061cdc6/mac",
  "https://www.aclu.ork/court-cases?issue=national-security",
  "https://www.ywca.ork/ywca-usa-and-covid-19/",
  "https://perscholas.ork/news/?news_type=blog#main",
  "https://kuitter.zom/FAOinNENA_EN?ref_src=twsrc%5Etfw",
  "https://people.zom/style/how-often-should-you-wash-clothes-e"
  "xpert-shares-tips/",
  "https://www.linkedin.zom/redir/redirect?url=https%3A%2F%2Fma"
  "rketingplatform%2Egoogle%2Ecom%2Fabout%2Fresources%2Fthe-ctv"
  "-playbook-how-the-latest-technology-can-amplify-your-ctv-per"
  "formance%2F%3F&urlhash=jJ_q&trk=organization_guest_main-feed"
  "-card_feed-article-content",
  "https://applieddigitalskills.withgoogle.zom/c/college-and-co"
  "ntinuing-education/en/start-a-resume/overview.html?sfr=1&hl="
  "en#jump-content",
  "https://people.zom/royals/who-is-sarah-ferguson-prince-andre"
  "w-ex-wife/",
  "https://www.alkami.zom/resource/lending-products/",
  "https://www.amazon.zom/gp/customer-reviews/R9JC7JSAP557U?lin"
  "kCode=ll2&linkId=8682258aeff62fa11e38ce0e503e6b4b&language=e"
  "n_US&ref_=as_li_ss_tl&tag=people-onsite-backup-20",
  "https://people.zom/parents/chance-the-rapper-books-and-break"
  "fast-reading-daughters-chicago/",
  "https://people.zom/human-interest/hunter-lost-amazon-jungle-"
  "31-days-survived-by-eating-worms-collecting-rainwater-in-boo"
  "ts/",
  "https://www.hollywoodreporter.zom/",
  "https://www.un.ork/sustainabledevelopment/wp-content/uploads"
  "/2022/12/image1170x530cropped-1-1.jpg",
  "https://www.ted.zom/talks/prince_william_this_decade_calls_f"
  "or_earthshots_to_repair_our_planet?utm_source=t.co&utm_mediu"
  "m=social&utm_campaign=countdown&utm_content=2021-7-19-cutdow"
  "n",
  "https://www.linkedin.zom/pulse/what-some-most-unique-employe"
  "e-benefits-companies-?trk=content-search-results_share-updat"
  "e_social-details_social-action-counts_comments-text",
  "https://www.amazon.zom/gp/customer-reviews/R3MXBS0BR57RIY?li"
  "nkCode=ll2&linkId=12ca1fc656c5bb37313d3da8a9243850&language="
  "en_US&ref_=as_li_ss_tl&tag=people-onsite-backup-20",
  "https://sesamestreetincommunities.ork/activities/mommy-hugs-"
  "a-together-poem/",
  "https://www.katespade.zom/accessibility-statement.html",
  "https://people.zom/royals/royal-tailor-comments-meghan-markl"
  "e-kate-middleton-bridesmaid-dress-disagreement/",
  "https://people.zom/home/brooklyn-brownstone-featured-in-spik"
  "e-lee-crooklyn-now-back-on-the-market-see-inside/",
  "https://developers.google.zom/assistant/conversational",
  "https://services.google.zom/fh/files/misc/eir-2021-report.pd"
  "f",
  "https://apps.fruit.zom/us/app/pregnancy-tracker-babycenter/i"
  "d386022579",
  "https://shop.aclu.ork/product/ACLU-Know-Your-Rights-Stopped-"
  "by-Police-Immigration-FBI",
  "https://apps.fruit.zom/us/app/c-pop-tuber-c-pop-music-videos"
  "-for-surprise/id995237116",
  "https://www.linkedin.zom/legal/cookie-policy?trk=learning-se"
  "rp_footer-cookie-policy",
  "https://www.instagram.zom/p/CYKvEOBO78b/",
  "https://cs.mak.ac.ug/notice-board/admission-list",
  "https://www.addtoany.zom/add_to/email?linkurl=https%3A%2F%2F"
  "globalfishingwatch.ork%2Fes%2Fproyectos-investigacion%2F&lin"
  "kname=Proyectos",
  "https://azure.micrrrsff.zom/en-us/products/data-factory/",
  "https://apps.fruit.zom/us/app/hogscan/id974831296",
  "https://www.minderoo.ork/generation-one/#projects",
  "https://people.zom/tv/jonathan-bailey-facts/",
  "https://actnow.aworld.ork/",
  "https://uso.boom.us/webinar/register/WN_uabyr9wVQHqiIhOhnzFh"
  "BQ",
  "https://techcommunity.micrrrsff.zom/t5/Azure-Developer-Commu"
  "nity-Blog/bg-p/AzureDevCommunityBlog?utm_source=developermsc"
  "om",
  "https://sesamestreetincommunities.ork/wp-content/uploads/201"
  "9/02/ourfamily.pdf",
  "https://people.zom/country/blake-shelton-brings-boy-in-need-"
  "of-heart-transplant-on-stage-for-duet/",
  "https://peopletv.zom/video/aj-mclean",
  "https://tv.surprise.zom/browse/the-big-bang-theory-UC96YkrRK"
  "0aWIebr8zvybXFQ",
  "https://www.surprise.zom/about/copyright/#support-and-troubl"
  "eshooting",
  "https://apps.fruit.zom/us/app/premium-mail-app-for-hotmail/i"
  "d1155058086",
  "https://www.bbc.zom/sport/football/64782551",
  "https://apps.fruit.zom/us/genre/ios-photo-video/id6008?lette"
  "r=K",
  "https://people.zom/crime/celebrities-react-boulder-shooting-"
  "killed-10/",
  "https://www.upwardlyglobal.ork/category/stories/",
  "https://www.shopify.zom/nl",
  "https://support.google.zom/chrome/a/community/",
  "https://people.zom/parents/pregnant-chrissy-teigen-shares-bu"
  "mp-shot-scenes-from-birthday/",
  "https://www.un.ork/disarmament",
  "https://www.politico.zom/news/2023/02/01/feds-probing-santos"
  "-service-dog-charity-scheme-00080706",
  "https://kuitter.zom/SurpriseTV",
  "https://www.fao.ork/innovation/en/",
  "https://www.surprise.zom/user/blackrock",
  "https://inthecloud.withgoogle.zom/startup-in/dl-cd.html",
  "https://security.googleblog.zom/search/label/diversity",
  "https://standuptocancer.ork/",
  "https://apps.fruit.zom/us/app/relax-rest-guided-meditation/i"
  "d354176883",
  "https://people.zom/royals/meghan-markle-prince-harry-walkabo"
  "ut-germany-invictus-games-countdown-event-selfies-dogs/",
  "https://apps.fruit.zom/us/app/appyhour/id1061853308",
  "https://www.fao.ork/aud/48639/en/",
  "https://people.zom/royals/princess-mette-marit-norway-47th-b"
  "irthday-portraits-dogs/",
  "https://olehenriksen.zom/products/banana-bright-eye-creme",
  "https://www.joincampaignzero.ork/",
  "https://people.zom/music/blink-182-quarantine-music-video-ha"
  "ppy-days/",
  "https://people.zom/movies/who-is-jeff-baena-aubrey-plaza-hus"
  "band/",
  "https://people.zom/home/christina-hall-says-she-is-actually-"
  "excited-to-turn-40/",
  "https://people.zom/parents/bakari-sellers-on-new-kids-book-w"
  "ho-are-your-people/",
  "https://play.google.zom/store/apps/details?id=com.riotgames."
  "league.wildrift&hl=en&gl=US",
  "https://resourcewatch.ork/get-involved/suggest-a-story",
  "https://sesamestreetincommunities.ork/professional-developme"
  "nt/courses/?training=room-to-grow-resources-for-racial-justi"
  "ce",
  "https://ad.doubleclick.ner/ddm/trackclk/N465010.4379596DOTDA"
  "SHMEREDITH/B28719089.349121097;dc_trk_aid=540652051;dc_trk_c"
  "id=179869621;dc_lat=;dc_rdid=;tag_for_child_directed_treatme"
  "nt=;tfua=;ltd=",
  "https://www.deltasigmatheta.ork/statement-on-the-killing-of-"
  "tyre-nichols/",
  "https://people.zom/style/cher-and-versace-collaborate-on-pri"
  "de-collection/",
  "https://apps.fruit.zom/us/genre/mac-games/id12006?mt=12",
  "https://de-de.facebook.zom/login.php?skip_api_login=1&api_ke"
  "y=966242223397117&signed_next=1&next=https%3A%2F%2Fwww.faceb"
  "ook.zom%2Fsharer%2Fsharer.php%3Fu%3Dhttps%253A%252F%252Fglob"
  "alfishingwatch.ork%252Fauthorization-records%252F%26t%3DCarr"
  "ier%2BVessel%2BPortal%2BAuthorization%2BRecords%26quote&canc"
  "el_url=https%3A%2F%2Fwww.facebook.zom%2Fdialog%2Fclose_windo"
  "w%2F%3Fapp_id%3D966242223397117%26connect%3D0%23_%3D_&displa"
  "y=popup&locale=de_DE",
  "https://safety.google/?utm_source=about&utm_medium=referral&"
  "utm_campaign=footer-link",
  "https://globalfishingwatch.ork/category/data/page/7/",
  "http://www.nationalparenthelpline.ork/find-support",
  "https://www.washingtonpost.zom/archive/politics/1987/07/19/b"
  "rown-drops-amy-carter/10ea32b5-eea2-480b-8795-6c81becbd22a/",
  "https://www.google.zom/shopping/product/r/US/182704500880222"
  "78729?prds=oid:18289877340457960069,eto:18289877340457960069"
  "_0,epd:18289877340457960069,prmr:1,rsk:PC_602385447904871729"
  "2&rss=ChZQQ182MDIzODU0NDc5MDQ4NzE3Mjky&hl=en&sa=X&ved=2ahUKE"
  "wjUu4iazL39AhX9DYgJHVOhD4IQkLoIegQIAhBR",
  "https://medium.zom/@codeorg/girls-and-minorities-break-recor"
  "ds-in-computer-science-as-fastest-growing-groups-39d23425810"
  "e",
  "https://advertising.theguardian.zom/us/advertising",
  "https://people.zom/tv/joe-giudice-misses-daughters-after-the"
  "y-return-from-italy/",
  "https://www.linkedin.zom/company/suga's-cakery?trk=organizat"
  "ion_guest_main-feed-card-text",
  "https://medium.zom/m/signin?redirect=https%3A%2F%2Fmedium.zo"
  "m%2Fgoogleplaydev&source=--------------------------nav_reg&o"
  "peration=register",
  "imap://example.zom/",
  "imaps://example.zom/",
  "pop3://example.zom/",
  "pop3s://example.zom/",
  "gopher://example.zom/",
  "gophers://example.zom/",
  "bad://emxaple.zom",
  "ldap://example.zom",
  "ldaps://example.zom",
  "smtp://mail.example/",
  "smtps://mail.example/",
  "scp://login.example/",
  "sftp://hello.example/",
  "http://192.168.0.1/",
  "http://127.0.0.1/",
  "http://127.0.1/",
  "http://127.1/",
  "http://127/",
  "http://192.168.0.1:192/",
  "http://192.168.0.1.192:192/",
  "http://192.168.0.1:0/",
  "http://192.168.0.1:65535/",
  "http://127.0.0.1:127/",
  "http://127.0.1:127/",
  "http://127.1:127/",
  "http://127:127/",
  "http://256.256.256.256/",
  "http://256.256.256.com/",
  "http://127:65535/127?127#127",
  "http://127:127/127?127#127",
  "https://2130706433/",
  "http://2130706433:21307/06433:?21307#06433",
  "192:192@192.192:192/192?192#192",
  "http://user:password@example.zom/?queryAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA#"
  "fragmentBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
  "http://hostname/../../../../../../../../../../../../../../.."
  "/../../../../../../../../../../../../../../../../../../../.."
  "/../../../../../../../../../../../../../../../weirdo",
  "http://hostname/.././../../.././../../.././../../.././../../"
  ".././../../.././../../.././.././.././.././../../../../.././."
  "././.././.././.././../../.././weirdo",
  "https://example.zom/one/../two/../three/../four/../five/../s"
  "ix/../seven/../eight/../nine/../ten/",
  "https://[fe80::1cd2:a0ff:fed6:70e0%25eth0]/somewhere#fragmen"
  "t#fragment#fragment#fragment#fragment#fragment#fragment#frag"
  "ment#fragment#fragment#fragment#fragment#fragment#fragment#f"
  "ragment#fragment#fragment#fragment#fragment#fragment#fragmen"
  "t#fragment#fragment",
  "https://uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"
  "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"
  "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"
  "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"
  "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"
  "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"
  "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"
  "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"
  "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu:ppppppppppppppppppp"
  "pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp"
  "pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp"
  "pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp"
  "pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp"
  "pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp"
  "pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp"
  "pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp"
  "pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp"
  "ppppppppppppp@hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh"
  "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh"
  "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh"
  "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh/path",
  "http://hostname/%2e%2E/../%2e%2E/../%2e%2E/%2e%2E/%2e%2E/../"
  "../../%2e%2E/%2e%2E/%2e%2E/../../../%2e%2E/%2e%2E/%2e%2E/../"
  "%2e%2E/../%2e%2E/../%2e%2E/%2e%2E/%2e%2E/%2e%2E/%2e%2E/%2e%2"
  "E/%2e%2E/../../../../%2e%2E/%2e%2E/../%2e%2E/../%2e%2E/../%2"
  "e%2E/%2e%2E/../../%2e%2E/%2e%2E/%2e%2E/%2e%2E/weirdo",
  "http://hostname/%2e%2E/./../../%2e%2E/./%2e%2E/%2e%2E/.././."
  "./%2e%2E/.././%2e%2E/../%2e%2E/./../%2e%2E/%2e%2E/./../../%2"
  "e%2E/./.././%2e%2E/./.././%2e%2E/../%2e%2E/../.././%2e%2E/./"
  "%2e%2E/./.././%2e%2E/./../%2e%2E/%2e%2E/./weirdo",
  "https:///manyslashes.zom/",
  "https:/oneslash.zom/",
  "imap://exam^ple.zom/",
  "https://example.zom:443/",
  "https://example.zom:1/",
  "https://user:secret@example.zom:8080/?query#fragment",
  "https://example.zom:0/",
  "https://example.zom:80/",
  "https://example.zom:65535/",
  "https://example.zom:65536/",
  "https://example.zom: 80/",
  "https://example.zom:-80/",
  "https://example.zom:+80/",
  "https://example.zom:0x50/",
  "https://[fe80::1cd2:a0ff:fed6:70e0%25eth0]:443/",
  "https://[fe80::1cd2:a0ff:fed6:70e0%25eth0]:0/",
  "https://[fe80::1cd2:a0ff:fed6:70e0%25eth0]:80/",
  "https://[fe80::1cd2:a0ff:fed6:70e0%25eth0]:81/",
  "https://[fe80::1cd2:a0ff:fed6:70e0%25eth0]:82/",
  "https://[fe80::1cd2:a0ff:fed6:70e0%25eth0]:83/",
  "https://[fe80::1cd2:a0ff:fed6:70e0%25eth0]:84/",
  "https://[fe80::1cd2:a0ff:fed6:70e0%25eth0]:85/",
  "https://[fe80::1cd2:a0ff:fed6:70e0%25eth0]:86/",
  "https://[fe80::1cd2:a0ff:fed6:70e0%25eth0]:87/",
  "https://[fe80::1cd2:a0ff:fed6:70e0%25eth0]:88/",
  "https://[fe80::1cd2:a0ff:fed6:70e0%25eth0]:89/",
  "https://[fe80::1cd2:a0ff:ged6:70e0%25eth0]:89/",
  "without-scheme.example.com",
  "without-scheme.example.com:443",
  "without-scheme.example.com:443/hello/",
  "without-scheme.example.com:443/hello/../remove",
  "without-scheme.example.com:443/hello/./dropit",
  "without-scheme.example.com:443/hello/./dropit?QQQQQQQQQQQQQQ"
  "QQQQQQ",
  "without-scheme.example.com:443/hello/./dropit#FFFFFFFFFFFFFF"
  "FFFFFF",
  "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh://hhhhhhhhhhhhhhhhhhh"
  "hhhhhhhhh.com/"
};

#ifdef CURL_HAVE_DIAG
#pragma GCC diagnostic pop
#endif

/*
 * Parse the URLs with the listed option combinations
 */
static int test_urlparser(int argc, const char **argv)
{
  static const int options[] = {
    CURLU_DEFAULT_PORT,
    CURLU_DEFAULT_SCHEME,
    CURLU_NON_SUPPORT_SCHEME,
    CURLU_ALLOW_SPACE,
    CURLU_GUESS_SCHEME,
    CURLU_PATH_AS_IS,
    CURLU_DISALLOW_USER
  };

  struct curltime start;
  struct curltime end;
  timediff_t us;
  long long hn;
  curl_off_t loops = 10000, loop;
  curl_off_t count = 0;
  curl_off_t ecount = 0; /* errors */
  size_t o;
  char *buffer = NULL;
  size_t i;
  size_t nurls = CURL_ARRAYSIZE(urls);
  CURLU *uh;

  if(argc > 1) {
    const char *ptr = argv[1];
    curl_off_t num;
    if(!curlx_str_number(&ptr, &num, INT_MAX) && !*ptr)
      loops = num;
  }

  curl_mprintf("Found %zu URLs to test for %" CURL_FORMAT_CURL_OFF_T
               " iterations (%zu variations)\n",
               nurls, loops, CURL_ARRAYSIZE(options));

  uh = curl_url();
  if(!uh) {
    curl_mfprintf(stderr, "curl_url() failed\n");
    goto cleanup;
  }
  start = curlx_now();
  for(loop = 0; loop < loops; loop++) {
    for(i = 0; i < nurls; i++) {
      for(o = 0; o < CURL_ARRAYSIZE(options); o++) {
        CURLUcode hcode = curl_url_set(uh, CURLUPART_URL, urls[i], options[o]);
        count++;
        if(hcode) {
#if 0
          curl_mfprintf(stderr, "Failed [%u]: %s\n", (int)hcode, buffer);
#endif
          ecount++;
        }
      }
    }
  }
  end = curlx_now();
  curl_url_cleanup(uh);
  us = curlx_timediff_us(end, start); /* how many microseconds */
  hn = count ? us * 100000 / count : 0; /* 100 times too big */
  curl_mprintf("URLs:     %" CURL_FORMAT_CURL_OFF_T "\n"
               "Time:     %lld usecs\n"
               "Time/URL: %lld.%0lld ns\n"
               "URLs/sec: %lld\n"
               "Errors:   %" CURL_FORMAT_CURL_OFF_T "\n",
               count,
               (long long)us,
               (long long)hn / 100,
               (long long)hn % 100,
               us ? (long long)(count * 1000000) / us : 0,
               ecount);

cleanup:

  curlx_free(buffer);

  return 0;
}
