#ifndef HEADER_CURL_CONFIG_OS400_H
#define HEADER_CURL_CONFIG_OS400_H
/***************************************************************************
 *                                  _   _ ____  _
 *  Project                     ___| | | |  _ \| |
 *                             / __| | | | |_) | |
 *                            | (__| |_| |  _ <| |___
 *                             \___|\___/|_| \_\_____|
 *
 * Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
 *
 * This software is licensed as described in the file COPYING, which
 * you should have received as part of this distribution. The terms
 * are also available at https://curl.se/docs/copyright.html.
 *
 * You may opt to use, copy, modify, merge, publish, distribute and/or sell
 * copies of the Software, and permit persons to whom the Software is
 * furnished to do so, under the terms of the COPYING file.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 * SPDX-License-Identifier: curl
 *
 ***************************************************************************/

/* ================================================================ */
/*                Hand crafted config file for OS/400               */
/* ================================================================ */

#pragma enum(int)


/* ---------------------------------------------------------------- */
/* Global configuration parameters: normally generated by autoconf. */
/* ---------------------------------------------------------------- */

/* Location of default ca bundle */
/* Use the system keyring as the default CA bundle. */
#define CURL_CA_BUNDLE          "/QIBM/UserData/ICSS/Cert/Server/DEFAULT.KDB"


/* define "1" to use OpenSSL's built-in CA store */
/* #undef CURL_CA_FALLBACK */

/* If native CA store is enabled */
/* #undef CURL_CA_NATIVE */

/* Location of default ca path */
/* #undef CURL_CA_PATH */

/* If safe CA bundle search is enabled */
/* #undef CURL_CA_SEARCH_SAFE */

/* Default SSL backend */
/* #undef CURL_DEFAULT_SSL_BACKEND */

/* disable alt-svc */
/* #undef CURL_DISABLE_ALTSVC */

/* to disable AWS sig support */
/* #undef CURL_DISABLE_AWS */

/* to disable basic authentication */
/* #undef CURL_DISABLE_BASIC_AUTH */

/* to disable bearer authentication */
/* #undef CURL_DISABLE_BEARER_AUTH */

/* disable local binding support */
/* #undef CURL_DISABLE_BINDLOCAL */

/* If unsafe CA bundle search in PATH on Windows is disabled */
/* #undef CURL_DISABLE_CA_SEARCH */

/* to disable cookies support */
/* #undef CURL_DISABLE_COOKIES */

/* to disable DICT */
/* #undef CURL_DISABLE_DICT */

/* to disable digest authentication */
/* #undef CURL_DISABLE_DIGEST_AUTH */

/* disable DoH */
/* #undef CURL_DISABLE_DOH */

/* to disable FILE */
/* #undef CURL_DISABLE_FILE */

/* disable form API */
/* #undef CURL_DISABLE_FORM_API */

/* to disable FTP */
/* #undef CURL_DISABLE_FTP */

/* to disable curl_easy_options */
/* #undef CURL_DISABLE_GETOPTIONS */

/* to disable Gopher */
/* #undef CURL_DISABLE_GOPHER */

/* disable headers-api */
/* #undef CURL_DISABLE_HEADERS_API */

/* disable alt-svc */
/* #undef CURL_DISABLE_HSTS */

/* to disable HTTP */
/* #undef CURL_DISABLE_HTTP */

/* disable HTTP authentication */
/* #undef CURL_DISABLE_HTTP_AUTH */

/* to disable IMAP */
/* #undef CURL_DISABLE_IMAP */

/* to disable IPFS */
/* #undef CURL_DISABLE_IPFS */

/* to disable kerberos authentication */
/* #undef CURL_DISABLE_KERBEROS_AUTH */

/* to disable LDAP */
/* #undef CURL_DISABLE_LDAP */

/* to disable LDAPS */
/* #undef CURL_DISABLE_LDAPS */

/* to disable --libcurl C code generation option */
/* #undef CURL_DISABLE_LIBCURL_OPTION */

/* disable mime API */
/* #undef CURL_DISABLE_MIME */

/* to disable MQTT */
/* #undef CURL_DISABLE_MQTT */

/* to disable negotiate authentication */
/* #undef CURL_DISABLE_NEGOTIATE_AUTH */

/* disable netrc parsing */
/* #undef CURL_DISABLE_NETRC */

/* to disable NTLM support */
/* #undef CURL_DISABLE_NTLM */

/* if the OpenSSL configuration will not be loaded automatically */
/* #undef CURL_DISABLE_OPENSSL_AUTO_LOAD_CONFIG */

/* disable date parsing */
/* #undef CURL_DISABLE_PARSEDATE */

/* to disable POP3 */
/* #undef CURL_DISABLE_POP3 */

/* disable progress-meter */
/* #undef CURL_DISABLE_PROGRESS_METER */

/* to disable proxies */
/* #undef CURL_DISABLE_PROXY */

/* to disable RTSP */
/* #undef CURL_DISABLE_RTSP */

/* disable SHA-512/256 hash algorithm */
/* #undef CURL_DISABLE_SHA512_256 */

/* disable DNS shuffling */
/* #undef CURL_DISABLE_SHUFFLE_DNS */

/* to disable SMB/CIFS */
/* #undef CURL_DISABLE_SMB */

/* to disable SMTP */
/* #undef CURL_DISABLE_SMTP */

/* to disable socketpair support */
/* #undef CURL_DISABLE_SOCKETPAIR */

/* to disable TELNET */
/* #undef CURL_DISABLE_TELNET */

/* to disable TFTP */
/* #undef CURL_DISABLE_TFTP */

/* to disable verbose strings */
/* #undef CURL_DISABLE_VERBOSE_STRINGS */

/* disable WebSockets */
/* #undef CURL_DISABLE_WEBSOCKETS */

/* Definition to make a library symbol externally visible. */
#define CURL_EXTERN_SYMBOL

/* MIT Kerberos version */
/* #undef CURL_KRB5_VERSION */

/* cpu-machine-OS */
#ifndef CURL_OS
#define CURL_OS                 "OS/400"
#endif

/* built with multiple SSL backends */
/* #undef CURL_WITH_MULTI_SSL */

/* Define to the type of arg 2 for gethostname. */
/* #undef GETHOSTNAME_TYPE_ARG2 */

/* Define to 1 if you have the 'accept4' function. */
/* #undef HAVE_ACCEPT4 */

/* Define to 1 if you have the alarm function. */
#define HAVE_ALARM              1

/* Define to 1 if you have the 'arc4random' function. */
/* #undef HAVE_ARC4RANDOM */

/* Define if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H        1

/* Define to 1 if you have _Atomic support. */
/* #undef HAVE_ATOMIC */

/* Define to 1 if you have the basename function. */
/* #undef HAVE_BASENAME */

/* Define to 1 if bool is an available type. */
/* #undef HAVE_BOOL_T */

/* if BROTLI is in use */
/* #undef HAVE_BROTLI */

/* Define to 1 if you have the <brotli/decode.h> header file. */
/* #undef HAVE_BROTLI_DECODE_H */

/* Define to 1 if you have the __builtin_available function. */
/* #undef HAVE_BUILTIN_AVAILABLE */

/* Define to 1 if you have the clock_gettime function and monotonic timer. */
/* #undef HAVE_CLOCK_GETTIME_MONOTONIC */

/* Define to 1 if you have the clock_gettime function and raw monotonic timer.
   */
/* #undef HAVE_CLOCK_GETTIME_MONOTONIC_RAW */

/* Define to 1 if you have the closesocket function. */
/* #undef HAVE_CLOSESOCKET */

/* Define to 1 if you have the CloseSocket camel case function. */
/* #undef HAVE_CLOSESOCKET_CAMEL */

/* Define to 1 if you have the fseeko declaration */
/* #undef HAVE_DECL_FSEEKO */

/* if you have the function DES_ecb_encrypt */
/* #undef HAVE_DES_ECB_ENCRYPT */

/* if you have <dirent.h> */
#define HAVE_DIRENT_H

/* Define to 1 if you have the <dlfcn.h> header file. */
/* #undef HAVE_DLFCN_H */

/* Define to 1 if you have the 'eventfd' function. */
/* #undef HAVE_EVENTFD */

/* Define to 1 if you have the fcntl function. */
#define HAVE_FCNTL              1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H            1

/* Define to 1 if you have a working fcntl O_NONBLOCK function. */
#define HAVE_FCNTL_O_NONBLOCK   1

/* Define to 1 if you have the 'fnmatch' function. */
/* #undef HAVE_FNMATCH */

/* Define to 1 if you have the freeaddrinfo function. */
#define HAVE_FREEADDRINFO       1

/* Define to 1 if you have the 'fseeko' function. */
/* #undef HAVE_FSEEKO */

/* Define to 1 if you have the fsetxattr function. */
/* #undef HAVE_FSETXATTR */

/* fsetxattr() takes 5 args */
/* #undef HAVE_FSETXATTR_5 */

/* fsetxattr() takes 6 args */
/* #undef HAVE_FSETXATTR_6 */

/* Define to 1 if you have the ftruncate function. */
#define HAVE_FTRUNCATE                  1

/* Define to 1 if you have a working getaddrinfo function. */
#define HAVE_GETADDRINFO                1

/* Define to 1 if the getaddrinfo function is thread-safe. */
#define HAVE_GETADDRINFO_THREADSAFE     1

/* Define to 1 if you have the 'geteuid' function. */
#define HAVE_GETEUID                    1

/* Define to 1 if you have the gethostbyname_r function. */
/* OS400 supports a 3-argument ASCII version of gethostbyname_r(), but its
 *  prototype is incompatible with the "standard" one (1st argument is not
 *  const). However, getaddrinfo() is supported (ASCII version defined as
 *  a local wrapper in setup-os400.h) in a thread-safe way: we can then
 *  configure getaddrinfo() as such and get rid of gethostbyname_r() without
 *  loss of thread-safeness. */
/* #undef HAVE_GETHOSTBYNAME_R */

/* gethostbyname_r() takes 3 args */
/* #undef HAVE_GETHOSTBYNAME_R_3 */

/* gethostbyname_r() takes 5 args */
/* #undef HAVE_GETHOSTBYNAME_R_5 */

/* gethostbyname_r() takes 6 args */
/* #undef HAVE_GETHOSTBYNAME_R_6 */

/* Define to 1 if you have the gethostname function. */
#define HAVE_GETHOSTNAME        1

/* Define to 1 if you have a working getifaddrs function. */
/* #undef HAVE_GETIFADDRS */

/* Define to 1 if you have the 'getpass_r' function. */
/* #undef HAVE_GETPASS_R */

/* Define to 1 if you have the getpeername function. */
#define HAVE_GETPEERNAME        1

/* Define to 1 if you have the 'getppid' function. */
#define HAVE_GETPPID            1

/* Define to 1 if you have the 'getpwuid' function. */
#define HAVE_GETPWUID           1

/* Define to 1 if you have the 'getpwuid_r' function. */
/* #undef HAVE_GETPWUID_R */

/* Define to 1 if you have the 'getrlimit' function. */
/* #undef HAVE_GETRLIMIT */

/* Define to 1 if you have the getsockname function. */
#define HAVE_GETSOCKNAME        1

/* Define to 1 if you have the 'gettimeofday' function. */
#define HAVE_GETTIMEOFDAY       1

/* Define to 1 if you have a working glibc-style strerror_r function. */
/* #undef HAVE_GLIBC_STRERROR_R */

/* Define to 1 if you have a working gmtime_r function. */
/* #undef HAVE_GMTIME_R */

/* if you have the function gnutls_srp_verifier */
/* #undef HAVE_GNUTLS_SRP */

/* Define to 1 if you have the <gsasl.h> header file. */
/* #undef HAVE_GSASL_H */

/* if you have GSS-API libraries */
#define HAVE_GSSAPI

/* Define to 1 if you have the <gssapi/gssapi_generic.h> header file. */
/* #undef HAVE_GSSAPI_GSSAPI_GENERIC_H */

/* Define to 1 if you have the <gssapi/gssapi.h> header file. */
/* #undef HAVE_GSSAPI_GSSAPI_H */

/* Define to 1 if you have the <gssapi/gssapi_krb5.h> header file. */
/* #undef HAVE_GSSAPI_GSSAPI_KRB5_H */

/* if you have GNU GSS */
/* #undef HAVE_GSSGNU */

/* Define to 1 if you have the <idn2.h> header file. */
/* #undef HAVE_IDN2_H */

/* Define to 1 if you have the <ifaddrs.h> header file. */
/* #undef HAVE_IFADDRS_H */

/* Define to 1 if you have the 'if_nametoindex' function. */
/* #undef HAVE_IF_NAMETOINDEX */

/* Define to 1 if you have an IPv6 capable working inet_ntop function. */
/* #undef HAVE_INET_NTOP */

/* Define to 1 if you have an IPv6 capable working inet_pton function. */
/* #undef HAVE_INET_PTON */

/* Define to 1 if you have the ioctlsocket function. */
/* #undef HAVE_IOCTLSOCKET */

/* Define to 1 if you have the IoctlSocket camel case function. */
/* #undef HAVE_IOCTLSOCKET_CAMEL */

/* Define to 1 if you have a working IoctlSocket camel case FIONBIO function.
   */
/* #undef HAVE_IOCTLSOCKET_CAMEL_FIONBIO */

/* Define to 1 if you have a working ioctlsocket FIONBIO function. */
/* #undef HAVE_IOCTLSOCKET_FIONBIO */

/* Define to 1 if you have a working ioctl FIONBIO function. */
#define HAVE_IOCTL_FIONBIO      1

/* Define to 1 if you have a working ioctl SIOCGIFADDR function. */
#define HAVE_IOCTL_SIOCGIFADDR  1

/* Define to 1 if you have the <io.h> header file. */
/* #undef HAVE_IO_H */

/* Define to 1 if you have the lber.h header file. */
#define HAVE_LBER_H             1

/* Define to 1 if you have the ldap.h header file. */
#define HAVE_LDAP_H             1

/* Define to 1 if you have the 'ldap_init_fd' function. */
/* #undef HAVE_LDAP_INIT_FD */

/* Use LDAPS implementation */
/* #undef HAVE_LDAP_SSL */

/* Define to 1 if you have the ldap_ssl.h header file. */
/* #undef HAVE_LDAP_SSL_H */

/* Define to 1 if you have the 'ldap_url_parse' function. */
/* #define HAVE_LDAP_URL_PARSE     1 */   /* Disabled because of an IBM bug. */

/* Define to 1 if you have the 'brotlidec' library (-lbrotlidec). */
/* #undef HAVE_LIBBROTLIDEC */

/* Define to 1 if you have the <libgen.h> header file. */
/* #undef HAVE_LIBGEN_H */

/* Define to 1 if you have the `idn2' library (-lidn2). */
/* #undef HAVE_LIBIDN2 */

/* Define to 1 if you have the <libpsl.h> header file. */
/* #undef HAVE_LIBPSL_H */

/* Define to 1 if you have the <librtmp/rtmp.h> header file. */
/* #undef HAVE_LIBRTMP_RTMP_H */

/* Define to 1 if you have the 'ssh' library (-lssh). */
/* #undef HAVE_LIBSSH */

/* Define to 1 if you have the 'ssh2' library (-lssh2). */
/* #undef HAVE_LIBSSH2 */

/* Define to 1 if you have the 'ssl' library (-lssl). */
/* #undef HAVE_LIBSSL */

/* if zlib is available. */
/* #undef HAVE_LIBZ */

/* Define to 1 if you have the 'zstd' library (-lzstd). */
/* #undef HAVE_LIBZSTD */

/* Define to 1 if you have the <linux/tcp.h> header file. */
/* #undef HAVE_LINUX_TCP_H */

/* Define to 1 if you have the <locale.h> header file. */
/* #undef HAVE_LOCALE_H */

/* Define to 1 if you have a working localtime_r function. */
#define HAVE_LOCALTIME_R        1

/* Define to 1 if you have the 'mach_absolute_time' function. */
/* #undef HAVE_MACH_ABSOLUTE_TIME */

/* Define to 1 if you have the 'mbedtls_des_crypt_ecb' function. */
/* #undef HAVE_MBEDTLS_DES_CRYPT_ECB */

/* Define to 1 if you have the memrchr function or macro. */
/* #undef HAVE_MEMRCHR */

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H            1

/* Define to 1 if you have the <netinet/in6.h> header file. */
/* #undef HAVE_NETINET_IN6_H */

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H       1

/* Define to 1 if you have the <netinet/tcp.h> header file. */
#define HAVE_NETINET_TCP_H      1

/* Define to 1 if you have the <netinet/udp.h> header file. */
#define HAVE_NETINET_UDP_H      1

/* Define to 1 if you have the <net/if.h> header file. */
#define HAVE_NET_IF_H           1

/* Define to 1 if you have the <nghttp2/nghttp2.h> header file. */
/* #undef HAVE_NGHTTP2_NGHTTP2_H */

/* Define to 1 if you have the <nghttp3/nghttp3.h> header file. */
/* #undef HAVE_NGHTTP3_NGHTTP3_H */

/* Define to 1 if you have the <ngtcp2/ngtcp2_crypto.h> header file. */
/* #undef HAVE_NGTCP2_NGTCP2_CRYPTO_H */

/* Define to 1 if you have the <ngtcp2/ngtcp2.h> header file. */
/* #undef HAVE_NGTCP2_NGTCP2_H */

/* if you have opendir */
#define HAVE_OPENDIR

/* Define to 1 if you have the <openssl/crypto.h> header file. */
/* #undef HAVE_OPENSSL_CRYPTO_H */

/* Define to 1 if you have the <openssl/err.h> header file. */
/* #undef HAVE_OPENSSL_ERR_H */

/* Define to 1 if you have the <openssl/pem.h> header file. */
/* #undef HAVE_OPENSSL_PEM_H */

/* Define to 1 if you have the <openssl/rsa.h> header file. */
/* #undef HAVE_OPENSSL_RSA_H */

/* if you have the functions SSL_CTX_set_srp_username and
   SSL_CTX_set_srp_password */
/* #undef HAVE_OPENSSL_SRP */

/* Define to 1 if you have the <openssl/ssl.h> header file. */
/* #undef HAVE_OPENSSL_SSL_H */

/* Define to 1 if you have the 'pipe' function. */
#define HAVE_PIPE               1

/* Define to 1 if you have the 'pipe2' function. */
/* #undef HAVE_PIPE2 */

/* Define to 1 if you have the 'poll' function. */
/* #undef HAVE_POLL */

/* Define to 1 if you have the <poll.h> header file. */
/* #undef HAVE_POLL_H */

/* Define to 1 if you have a working POSIX-style strerror_r function. */
/* #undef HAVE_POSIX_STRERROR_R */

/* Define to 1 if you have the <proto/bsdsocket.h> header file. */
/* #undef HAVE_PROTO_BSDSOCKET_H */

/* if you have <pthread.h> */
#define HAVE_PTHREAD_H          1

/* Define to 1 if you have the <pwd.h> header file. */
#define HAVE_PWD_H              1

/* Define to 1 if you have the 'quiche_conn_set_qlog_fd' function. */
/* #undef HAVE_QUICHE_CONN_SET_QLOG_FD */

/* Define to 1 if you have the <quiche.h> header file. */
/* #undef HAVE_QUICHE_H */

/* Define to 1 if you have the 'realpath' function. */
/* #undef HAVE_REALPATH */

/* Define to 1 if you have the recv function. */
#define HAVE_RECV               1

/* Define to 1 if symbol `sa_family_t' exists */
#define HAVE_SA_FAMILY_T        1

/* Define to 1 if you have the 'sched_yield' function. */
/* #undef HAVE_SCHED_YIELD */

/* Define to 1 if you have the select function. */
#define HAVE_SELECT             1

/* Define to 1 if you have the send function. */
#define HAVE_SEND               1

/* Define to 1 if you have the 'sendmmsg' function. */
/* #undef HAVE_SENDMMSG */

/* Define to 1 if you have the 'sendmsg' function. */
#define HAVE_SENDMSG            1

/* Define to 1 if you have the 'setlocale' function. */
/* #undef HAVE_SETLOCALE */

/* Define to 1 if you have the 'setrlimit' function. */
/* #undef HAVE_SETRLIMIT */

/* Define to 1 if you have the sigaction function. */
#define HAVE_SIGACTION          1

/* Define to 1 if you have the siginterrupt function. */
/* #undef HAVE_SIGINTERRUPT */

/* Define to 1 if you have the signal function. */
/* #undef HAVE_SIGNAL */

/* Define to 1 if you have the sigsetjmp function or macro. */
/* #undef HAVE_SIGSETJMP */

/* Define to 1 if you have the 'snprintf' function. */
/* #undef HAVE_SNPRINTF */

/* Define to 1 if struct sockaddr_in6 has the sin6_scope_id member */
#define HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID 1

/* Define to 1 if you have the socket function. */
/* #undef HAVE_SOCKET */

/* Define to 1 if you have the socketpair function. */
#define HAVE_SOCKET             1

/* Define to 1 if you have the 'SSL_set0_wbio' function. */
/* #undef HAVE_SSL_SET0_WBIO */

/* Define to 1 if you have the 'SSL_set1_ech_config_list' function. */
/* #undef HAVE_SSL_SET1_ECH_CONFIG_LIST */

/* Define to 1 if you have the 'SSL_set_quic_tls_cbs' function. */
/* #undef HAVE_SSL_SET_QUIC_TLS_CBS */

/* Define to 1 if you have the 'SSL_set_quic_use_legacy_codepoint' function.
   */
/* #undef HAVE_SSL_SET_QUIC_USE_LEGACY_CODEPOINT */

/* Define to 1 if you have the <stdatomic.h> header file. */
/* #undef HAVE_STDATOMIC_H */

/* Define to 1 if you have the <stdbool.h> header file. */
#define HAVE_STDBOOL_H          1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H           1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H            1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H           1

/* Define to 1 if you have the strcasecmp function. */
/* #undef HAVE_STRCASECMP */

/* Define to 1 if you have the strcmpi function. */
/* #undef HAVE_STRCMPI */

/* Define to 1 if you have the strerror_r function. */
/* #undef HAVE_STRERROR_R */

/* Define to 1 if you have the stricmp function. */
#define HAVE_STRICMP            1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H          1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H           1

/* Define to 1 if you have the <stropts.h> header file. */
/* #undef HAVE_STROPTS_H */

/* if struct sockaddr_storage is defined */
#define HAVE_STRUCT_SOCKADDR_STORAGE

/* Define to 1 if you have the timeval struct. */
#define HAVE_STRUCT_TIMEVAL     1

/* Define to 1 if suseconds_t is an available type. */
/* #undef HAVE_SUSECONDS_T */

/* Define to 1 if you have the <sys/eventfd.h> header file. */
/* #undef HAVE_SYS_EVENTFD_H */

/* Define to 1 if you have the <sys/filio.h> header file. */
/* #undef HAVE_SYS_FILIO_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H        1

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H        1

/* Define to 1 if you have the <sys/poll.h> header file. */
/* #undef HAVE_SYS_POLL_H */

/* Define to 1 if you have the <sys/resource.h> header file. */
#define HAVE_SYS_RESOURCE_H     1

/* Define to 1 if you have the <sys/select.h> header file. */
/* #undef HAVE_SYS_SELECT_H */

/* Define to 1 if you have the <sys/sockio.h> header file. */
/* #undef HAVE_SYS_SOCKIO_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H         1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H        1

/* Define to 1 if you have the <sys/un.h> header file. */
#define HAVE_SYS_UN_H           1

/* Define to 1 if you have the <sys/utime.h> header file. */
/* #undef HAVE_SYS_UTIME_H */

/* Define to 1 if you have the <sys/xattr.h> header file. */
/* #undef HAVE_SYS_XATTR_H */

/* Define to 1 if you have the <termios.h> header file. */
/* #undef HAVE_TERMIOS_H */

/* Define to 1 if you have the <termio.h> header file. */
/* #undef HAVE_TERMIO_H */

/* Define this if time_t is unsigned */
/* #undef HAVE_TIME_T_UNSIGNED */

/* Define to 1 if you have the <unicode/uidna.h> header file. */
#define HAVE_UNICODE_UIDNA_H    1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H           1

/* Define to 1 if you have the 'utime' function. */
#define HAVE_UTIME              1

/* Define to 1 if you have the 'utimes' function. */
/* #undef HAVE_UTIMES */

/* Define to 1 if you have the <utime.h> header file. */
#define HAVE_UTIME_H            1

/* Define to 1 if you have the <uv.h> header file. */
/* #undef HAVE_UV_H */

/* Define to 1 if you have the 'wolfSSL_BIO_new' function. */
/* #undef HAVE_WOLFSSL_BIO_NEW */

/* Define to 1 if you have the 'wolfSSL_BIO_set_shutdown' function. */
/* #undef HAVE_WOLFSSL_BIO_SET_SHUTDOWN */

/* Define to 1 if you have the 'wolfSSL_CTX_GenerateEchConfig' function. */
/* #undef HAVE_WOLFSSL_CTX_GENERATEECHCONFIG */

/* Define to 1 if you have the 'wolfSSL_DES_ecb_encrypt' function. */
/* #undef HAVE_WOLFSSL_DES_ECB_ENCRYPT */

/* Define to 1 if you have the 'wolfSSL_get_peer_certificate' function. */
/* #undef HAVE_WOLFSSL_GET_PEER_CERTIFICATE */

/* Define to 1 if you have the 'wolfSSL_set_quic_use_legacy_codepoint'
   function. */
/* #undef HAVE_WOLFSSL_SET_QUIC_USE_LEGACY_CODEPOINT */

/* Define to 1 if you have the 'wolfSSL_UseALPN' function. */
/* #undef HAVE_WOLFSSL_USEALPN */

/* Define this symbol if your OS supports changing the contents of argv */
/* #undef HAVE_WRITABLE_ARGV */

/* if libzstd is in use */
/* #undef HAVE_ZSTD */

/* Define to 1 if you have the <zstd.h> header file. */
/* #undef HAVE_ZSTD_H */

/* Define to the subdirectory where libtool stores uninstalled libraries. */
/* #undef LT_OBJDIR */

/* Define to 1 if you need the lber.h header file even with ldap.h */
/* #undef NEED_LBER_H */

/* Define to 1 if _REENTRANT preprocessor symbol must be defined. */
/* #undef NEED_REENTRANT */

/* Define to 1 if _THREAD_SAFE preprocessor symbol must be defined. */
/* #undef NEED_THREAD_SAFE */

/* openssl with new QUIC API */
/* #undef OPENSSL_QUIC_API2 */

/* Name of package */
/* #undef PACKAGE */

/* Define to the address where bug reports for this package should be sent. */
/* #undef PACKAGE_BUGREPORT */

/* Define to the full name of this package. */
/* #undef PACKAGE_NAME */

/* Define to the full name and version of this package. */
/* #undef PACKAGE_STRING */

/* Define to the one symbol short name of this package. */
/* #undef PACKAGE_TARNAME */

/* Define to the home page for this package. */
/* #undef PACKAGE_URL */

/* Define to the version of this package. */
/* #undef PACKAGE_VERSION */

/* Size of curl_off_t in number of bytes */
#define SIZEOF_CURL_OFF_T       8

/* Size of curl_socket_t in number of bytes */
#define SIZEOF_CURL_SOCKET_T    4

/* Size of int in number of bytes */
#define SIZEOF_INT              4

/* Size of long in number of bytes */
#define SIZEOF_LONG             4

/* Size of off_t in number of bytes */
#define SIZEOF_OFF_T            8       /* _LARGE_FILES (*IFS64IO) version. */

/* Size of size_t in number of bytes */
#define SIZEOF_SIZE_T           4

/* Size of time_t in number of bytes */
#define SIZEOF_TIME_T           4

/* Define to 1 if all of the C89 standard headers exist (not just the ones
   required in a freestanding environment). This macro is provided for
   backward compatibility; new code need not use it. */
#define STDC_HEADERS            1

/* if AmiSSL is in use */
/* #undef USE_AMISSL */

/* if AppleIDN */
/* #undef USE_APPLE_IDN */

/* enable Apple OS certificate validation */
/* #undef USE_APPLE_SECTRUST */

/* Define to enable c-ares support */
/* #undef USE_ARES */

/* if libbacktrace is in use */
/* #undef USE_BACKTRACE */

/* if ECH support is available */
/* #undef USE_ECH */

/* if GnuTLS is enabled */
/* #undef USE_GNUTLS */

/* GSASL support enabled */
/* #undef USE_GSASL */

/* enable HTTPS RR support */
/* #undef USE_HTTPSRR */

/* Define if you want to enable IPv6 support */
#define USE_IPV6

/* if libpsl is in use */
/* #undef USE_LIBPSL */

/* if librtmp is in use */
/* #undef USE_LIBRTMP */

/* if libssh is in use */
/* #undef USE_LIBSSH */

/* if libssh2 is in use */
/* #undef USE_LIBSSH2 */

/* if libuv is in use */
/* #undef USE_LIBUV */

/* if mbedTLS is enabled */
/* #undef USE_MBEDTLS */

/* if nghttp2 is in use */
/* #undef USE_NGHTTP2 */

/* if nghttp3 is in use */
/* #undef USE_NGHTTP3 */

/* if ngtcp2 is in use */
/* #undef USE_NGTCP2 */

/* Use OpenLDAP-specific code */
/* #undef USE_OPENLDAP */

/* if OpenSSL is in use */
/* #undef USE_OPENSSL */

/* if quiche is in use */
/* #undef USE_QUICHE */

/* if Rustls is enabled */
/* #undef USE_RUSTLS */

/* to enable Windows native SSL/TLS support */
/* #undef USE_SCHANNEL */

/* if SSL session export support is available */
/* #undef USE_SSLS_EXPORT */

/* if you want POSIX threaded DNS lookup */
/* #undef USE_THREADS_POSIX */

/* if you want Win32 threaded DNS lookup */
/* #undef USE_THREADS_WIN32 */

/* Use TLS-SRP authentication */
/* #undef USE_TLS_SRP */

/* Use Unix domain sockets */
#define USE_UNIX_SOCKETS

/* if Watt-32 is in use */
/* #undef USE_WATT32 */

/* Define to 1 if you are building a Windows target with crypto API support.
   */
/* #undef USE_WIN32_CRYPTO */

/* Define to 1 if you have the `normaliz' (WinIDN) library (-lnormaliz). */
/* #undef USE_WIN32_IDN */

/* Use Windows LDAP implementation */
/* #undef USE_WIN32_LDAP */

/* to enable SSPI support */
/* #undef USE_WINDOWS_SSPI */

/* if wolfSSL is enabled */
/* #undef USE_WOLFSSL */

/* Version number of package */
/* #undef VERSION */

/* Define to 1 if OS is AIX. */
#ifndef _ALL_SOURCE
#  undef _ALL_SOURCE
#endif

/* Number of bits in a file offset, on hosts where this is settable. */
/* #undef _FILE_OFFSET_BITS */

/* Define to 1 on platforms where this makes off_t a 64-bit type.
   Let it be defined by system header files. */
/* #define _LARGE_FILES            1 */

/* Number of bits in time_t, on hosts where this is settable. */
/* #undef _TIME_BITS */

/* Define to 1 on platforms where this makes time_t a 64-bit type. */
/* #undef __MINGW_USE_VC2005_COMPAT */

/* Define to empty if 'const' does not conform to ANSI C. */
/* #undef const */

/* Define as 'unsigned int' if <stddef.h> does not define. */
/* #undef size_t */

/* the signed version of size_t */
/* #undef ssize_t */


/* ---------------------------------------------------------------- */
/*          recv/send parameter types (see lib/functypes.h)         */
/* ---------------------------------------------------------------- */

/* int recv(int, char *, int, int); */
#define RECV_TYPE_ARG1          int
#define RECV_TYPE_ARG2          char *
#define RECV_TYPE_ARG3          int
#define RECV_TYPE_ARG4          int
#define RECV_TYPE_RETV          int

/* int send(int, char *, int, int); */
#define SEND_TYPE_ARG1          int
#define SEND_NONCONST_ARG2
#define SEND_TYPE_ARG2          char *
#define SEND_TYPE_ARG3          int
#define SEND_TYPE_ARG4          int
#define SEND_TYPE_RETV          int


/* ---------------------------------------------------------------- */
/*           Additional definitions specific to OS/400              */
/* ---------------------------------------------------------------- */

/* The <gssapi.h> header file is in the main system include directory. */
#define HAVE_GSSAPI_H

/* Define to use the OS/400 crypto library. */
#define USE_OS400CRYPTO

/* The following definition is required on OS/400 to enable strcmpi(),
   stricmp() and strdup(). */
#define __cplusplus__strings__

/* The following must be defined BEFORE system header files inclusion. */

#define __ptr128                       /* No teraspace. */
#define qadrt_use_fputc_inline         /* Generate fputc() wrapper inline. */
#define qadrt_use_fread_inline         /* Generate fread() wrapper inline. */
#define qadrt_use_fwrite_inline        /* Generate fwrite() wrapper inline. */

#endif /* HEADER_CURL_CONFIG_OS400_H */
