# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# SPDX-License-Identifier: curl

# https://docs.github.com/en/actions/tutorials/create-actions/create-a-composite-action
name: 'Install apt packages'
description: 'Installs apt packages for local workflows'

inputs:
  packages:
    description: 'Space-separated list of apt package names'
    required: true
  pip:
    description: 'optional requirements.txt filename'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'install (apt)'
      if: ${{ inputs.packages }}
      shell: bash
      env:
        PACKAGES: ${{ inputs.packages }}
      run: |
        ls -l /etc/apt/sources.list.d
        sudo find /etc/apt/sources.list.d -type f -not -name 'ubuntu.sources' -delete -print
        sudo sed -i 's/priority:1/priority:9/' /etc/apt/apt-mirrors.txt; cat /etc/apt/apt-mirrors.txt
        sudo apt-get -o Dpkg::Use-Pty=0 update
        sudo apt-get -o Dpkg::Use-Pty=0 install ${PACKAGES}

    - name: 'install (python)'
      if: ${{ inputs.pip }}
      shell: bash
      env:
        REQUIREMENTS: ${{ inputs.pip }}
      run: |
          python3 -m venv ~/venv
          ~/venv/bin/pip --disable-pip-version-check --no-input --no-cache-dir install --progress-bar off --prefer-binary -r ${REQUIREMENTS}
