.\" $Id$
.\"
.\" Copyright 1998 by the Massachusetts Institute of Technology.
.\"
.\" Permission to use, copy, modify, and distribute this
.\" software and its documentation for any purpose and without
.\" fee is hereby granted, provided that the above copyright
.\" notice appear in all copies and that both that copyright
.\" notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in
.\" advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\" M.I.T. makes no representations about the suitability of
.\" this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\"
.TH ARES_FREE_ERRMEM 3 "23 July 1998"
.SH NAME
ares_free_errmem \- Free memory allocated by ares_strerror
.SH SYNOPSIS
.nf
.B #include <ares.h>
.PP
.B void ares_free_errmem(char *\fIerrmem\fP)
.fi
.SH DESCRIPTION
The
.B ares_free_errmem
function frees any memory which might have been allocated by the
.BR ares_strerror (3)
function.  The parameter
.I errmem
should be set to the variable pointed to by the
.I memptr
argument previously passed to
.IR ares_strerror .
.SH SEE ALSO
.BR ares_strerror (3)
.SH AUTHOR
Greg Hudson, MIT Information Systems
.br
Copyright 1998 by the Massachusetts Institute of Technology.
