#!/bin/sh

if test -z "$ACLOCAL_FLAGS"; then
  ACLOCAL_FLAGS="-I m4"
else
  ACLOCAL_FLAGS="$ACLOCAL_FLAGS -I m4"
fi
export ACLOCAL_FLAGS
echo "cares buildconf: using ACLOCAL_FLAGS: $ACLOCAL_FLAGS"

${LIBTOOLIZE:-libtoolize} --copy --automake --force
${ACLOCAL:-aclocal} $ACLOCAL_FLAGS
${AUTOHEADER:-autoheader}
${AUTOCONF:-autoconf}
${AUTOMAKE:-automake} --add-missing
