#ifndef HEADER_FETCHMSG_H
#define HEADER_FETCHMSG_H
/***************************************************************************
 *                                  _   _ ____  _
 *  Project                     ___| | | |  _ \| |
 *                             / __| | | | |_) | |
 *                            | (__| |_| |  _ <| |___
 *                             \___|\___/|_| \_\_____|
 *
 * Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
 *
 * This software is licensed as described in the file COPYING, which
 * you should have received as part of this distribution. The terms
 * are also available at https://curl.se/docs/copyright.html.
 *
 * You may opt to use, copy, modify, merge, publish, distribute and/or sell
 * copies of the Software, and permit persons to whom the Software is
 * furnished to do so, under the terms of the COPYING file.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 * SPDX-License-Identifier: fetch
 *
 ***************************************************************************/

#pragma __member_alignment __save
#pragma __nomember_alignment

/*                                                                          */
/* FETCHMSG.H                                                                */
/*                                                                          */
/* SDL File Generated by VAX-11 Message V04-00 on 3-SEP-2008 13:33:54.09    */
/*                                                                          */
/* THESE VMS ERROR CODES ARE GENERATED BY TAKING APART THE FETCH.H           */
/* FILE AND PUTTING ALL THE FETCHE_* ENUM STUFF INTO THIS FILE,              */
/* FETCHMSG.MSG.  AN .SDL FILE IS CREATED FROM THIS FILE WITH                */
/* MESSAGE/SDL.  THE .H FILE IS CREATED USING THE FREEWARE SDL TOOL         */
/* AGAINST THE .SDL FILE WITH SDL/ALPHA/LANG=CC COMMAND.                    */
/*                                                                          */
/* WITH THE EXCEPTION OF FETCHE_OK, ALL OF THE MESSAGES ARE AT               */
/* THE ERROR SEVERITY LEVEL.  WITH THE EXCEPTION OF                         */
/* PEER_FAILED_VERIF, WHICH IS A SHORTENED FORM OF                          */
/* PEER_FAILED_VERIFICATION, THESE ARE THE SAME NAMES AS THE                */
/* FETCHE_ ONES IN INCLUDE/FETCH.H.  THE MESSAGE UTILITY MANUAL STATES        */
/* "THE COMBINED LENGTH OF THE PREFIX AND THE MESSAGE SYMBOL NAME CANNOT    */
/* EXCEED 31 CHARACTERS."  WITH A PREFIX OF FIVE THAT LEAVES US WITH 26     */
/* FOR THE MESSAGE NAME.                                                    */
/*                                                                          */
/* IF YOU UPDATE THIS FILE, UPDATE FETCHMSG_VMS.H SO THAT THEY ARE IN SYNC   */
/*                                                                          */

#define FETCH_FACILITY 3841
#define FETCH_OK 251756553
#define FETCH_UNSUPPORTED_PROTOCOL 251756562
#define FETCH_FAILED_INIT 251756570
#define FETCH_URL_MALFORMAT 251756578
#define FETCH_OBSOLETE4 251756586
#define FETCH_COULDNT_RESOLVE_PROXY 251756594
#define FETCH_COULDNT_RESOLVE_HOST 251756602
#define FETCH_COULDNT_CONNECT 251756610
#define FETCH_WEIRD_SERVER_REPLY 251756618
#define FETCH_FTP_WEIRD_SERVER_REPLY FETCH_WEIRD_SERVER_REPLY
#define FETCH_FTP_ACCESS_DENIED 251756626
#define FETCH_OBSOLETE10 251756634
#define FETCH_FTP_WEIRD_PASS_REPLY 251756642
#define FETCH_OBSOLETE12 251756650
#define FETCH_FTP_WEIRD_PASV_REPLY 251756658
#define FETCH_FTP_WEIRD_227_FORMAT 251756666
#define FETCH_FTP_CANT_GET_HOST 251756674
#define FETCH_OBSOLETE16 251756682
#define FETCH_FTP_COULDNT_SET_TYPE 251756690
#define FETCH_PARTIAL_FILE 251756698
#define FETCH_FTP_COULDNT_RETR_FILE 251756706
#define FETCH_OBSOLETE20 251756714
#define FETCH_QUOTE_ERROR 251756722
#define FETCH_HTTP_RETURNED_ERROR 251756730
#define FETCH_WRITE_ERROR 251756738
#define FETCH_OBSOLETE24 251756746
#define FETCH_UPLOAD_FAILED 251756754
#define FETCH_READ_ERROR 251756762
#define FETCH_OUT_OF_MEMORY 251756770
#define FETCH_OPERATION_TIMEOUTED 251756778
#define FETCH_OBSOLETE29 251756786
#define FETCH_FTP_PORT_FAILED 251756794
#define FETCH_FTP_COULDNT_USE_REST 251756802
#define FETCH_OBSOLETE32 251756810
#define FETCH_RANGE_ERROR 251756818
#define FETCH_HTTP_POST_ERROR 251756826
#define FETCH_SSL_CONNECT_ERROR 251756834
#define FETCH_BAD_DOWNLOAD_RESUME 251756842
#define FETCH_FILE_COULDNT_READ_FILE 251756850
#define FETCH_LDAP_CANNOT_BIND 251756858
#define FETCH_LDAP_SEARCH_FAILED 251756866
#define FETCH_OBSOLETE40 251756874
#define FETCH_FUNCTION_NOT_FOUND 251756882
#define FETCH_ABORTED_BY_CALLBACK 251756890
#define FETCH_BAD_FUNCTION_ARGUMENT 251756898
#define FETCH_OBSOLETE44 251756906
#define FETCH_INTERFACE_FAILED 251756914
#define FETCH_OBSOLETE46 251756922
#define FETCH_TOO_MANY_REDIRECTS 251756930
#define FETCH_UNKNOWN_TELNET_OPTION 251756938
#define FETCH_TELNET_OPTION_SYNTAX 251756946
#define FETCH_OBSOLETE50 251756954
#define FETCH_PEER_FAILED_VERIF 251756962
#define FETCH_GOT_NOTHING 251756970
#define FETCH_SSL_ENGINE_NOTFOUND 251756978
#define FETCH_SSL_ENGINE_SETFAILED 251756986
#define FETCH_SEND_ERROR 251756994
#define FETCH_RECV_ERROR 251757002
#define FETCH_OBSOLETE57 251757010
#define FETCH_SSL_CERTPROBLEM 251757018
#define FETCH_SSL_CIPHER 251757026
#define FETCH_SSL_CACERT 251757034
#define FETCH_BAD_CONTENT_ENCODING 251757042
#define FETCH_LDAP_INVALID_URL 251757050
#define FETCH_FILESIZE_EXCEEDED 251757058
#define FETCH_USE_SSL_FAILED 251757066
#define FETCH_SEND_FAIL_REWIND 251757074
#define FETCH_SSL_ENGINE_INITFAILED 251757082
#define FETCH_LOGIN_DENIED 251757090
#define FETCH_TFTP_NOTFOUND 251757098
#define FETCH_TFTP_PERM 251757106
#define FETCH_REMOTE_DISK_FULL 251757114
#define FETCH_TFTP_ILLEGAL 251757122
#define FETCH_TFTP_UNKNOWNID 251757130
#define FETCH_REMOTE_FILE_EXISTS 251757138
#define FETCH_TFTP_NOSUCHUSER 251757146
#define FETCH_CONV_FAILED 251757154
#define FETCH_CONV_REQD 251757162
#define FETCH_SSL_CACERT_BADFILE 251757170
#define FETCH_REMOTE_FILE_NOT_FOUND 251757178
#define FETCH_SSH 251757186
#define FETCH_SSL_SHUTDOWN_FAILED 251757194
#define FETCH_AGAIN 251757202
#define FETCH_SSL_CRL_BADFILE 251757210
#define FETCH_SSL_ISSUER_ERROR 251757218
#define FETCH_FETCH_LAST 251757226

#pragma __member_alignment __restore

#endif /* HEADER_FETCHMSG_H */
