#!/usr/bin/env perl
#***************************************************************************
#                                  _   _ ____  _
#  Project                     ___| | | |  _ \| |
#                             / __| | | | |_) | |
#                            | (__| |_| |  _ <| |___
#                             \___|\___/|_| \_\_____|
#
# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at https://curl.se/docs/copyright.html.
#
# You may opt to use, copy, modify, merge, publish, distribute and/or sell
# copies of the Software, and permit persons to whom the Software is
# furnished to do so, under the terms of the COPYING file.
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
# KIND, either express or implied.
#
# SPDX-License-Identifier: curl
#
###########################################################################

# provide all dir names to scan on the cmdline

sub convert {
    my ($dir)=@_;
    opendir(my $dh, $dir) || die "could not open $dir";
    my @cd = grep { /\.md\z/ && -f "$dir/$_" } readdir($dh);
    closedir $dh;

    for my $cd (@cd) {
        my $nroff = "$cd";
        $nroff =~ s/\.md\z/.3/;
        print "$dir/$cd = $dir/$nroff\n";
        system("./scripts/cd2nroff -d $dir $dir/$cd");
    }
}

for my $d (sort @ARGV) {
    convert($d);
}
