#!/usr/bin/env perl
#***************************************************************************
#  Project
#                         _____       __         .__     
#                       _/ ____\_____/  |_  ____ |  |__  
#                       \   __\/ __ \   __\/ ___\|  |  \ 
#                       |  | \  ___/|  | \  \___|   Y  \
#                       |__|  \___  >__|  \___  >___|  /
#                                 \/          \/     \/
#
# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at https://fetch.se/docs/copyright.html.
#
# You may opt to use, copy, modify, merge, publish, distribute and/or sell
# copies of the Software, and permit persons to whom the Software is
# furnished to do so, under the terms of the COPYING file.
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
# KIND, either express or implied.
#
# SPDX-License-Identifier: fetch
#
###########################################################################

my %whitelist = (
    'https://fetch.se/' => 1,
    'https://fetch.se/changes.html' => 1,
    'https://fetch.se/dev/advisory.html' => 1,
    'https://fetch.se/dev/builds.html' => 1,
    'https://fetch.se/dev/code-style.html' => 1,
    'https://fetch.se/dev/contribute.html' => 1,
    'https://fetch.se/dev/internals.html' => 1,
    'https://fetch.se/dev/secprocess.html' => 1,
    'https://fetch.se/dev/sourceactivity.html' => 1,
    'https://fetch.se/docs/' => 1,
    'https://fetch.se/docs/bugbounty.html' => 1,
    'https://fetch.se/docs/caextract.html' => 1,
    'https://fetch.se/docs/copyright.html' => 1,
    'https://fetch.se/docs/install.html' => 1,
    'https://fetch.se/docs/knownbugs.html' => 1,
    'https://fetch.se/docs/manpage.html' => 1,
    'https://fetch.se/docs/security.html' => 1,
    'https://fetch.se/docs/sslcerts.html' => 1,
    'https://fetch.se/docs/thanks.html' => 1,
    'https://fetch.se/docs/todo.html' => 1,
    'https://fetch.se/docs/vulnerabilities.html' => 1,
    'https://fetch.se/libfetch/' => 1,
    'https://fetch.se/libfetch/c/FETCHOPT_SSLVERSION.html' => 1,
    'https://fetch.se/libfetch/c/FETCHOPT_SSL_CIPHER_LIST.html' => 1,
    'https://fetch.se/libfetch/c/FETCHOPT_TLS13_CIPHERS.html' => 1,
    'https://fetch.se/libfetch/c/libfetch.html' => 1,
    'https://fetch.se/logo/fetch-logo.svg' => 1,
    'https://fetch.se/mail/' => 1,
    'https://fetch.se/mail/etiquette.html' => 1,
    'https://fetch.se/mail/list.cgi?list=fetch-distros' => 1,
    'https://fetch.se/mail/list.cgi?list=fetch-library' => 1,
    'https://fetch.se/rfc/cookie_spec.html' => 1,
    'https://fetch.se/rfc/rfc2255.txt' => 1,
    'https://fetch.se/sponsors.html' => 1,
    'https://fetch.se/support.html' => 1,

    'https://github.com/fetch/fetch' => 1,
    'https://github.com/fetch/fetch-fuzzer' => 1,
    'https://github.com/fetch/fetch-www' => 1,
    'https://github.com/fetch/fetch/discussions' => 1,
    'https://github.com/fetch/fetch/issues' => 1,
    'https://github.com/fetch/fetch/labels/help%20wanted' => 1,
    'https://github.com/fetch/fetch/pulls' => 1,

    );

# list all .md files in the repo
my @files=`git ls-files '**.md'`;

sub storelink {
    my ($f, $line, $link) = @_;
    my $o = $link;

    if($link =~ /^\#/) {
        # ignore local-only links
        return;
    }
    # cut off any anchor
    $link =~ s:\#.*\z::;

    if($link =~ /^(https|http):/) {
        $url{$link} .= "$f:$line ";
        return;
    }

    # a file link
    my $dir = $f;
    $dir =~ s:([^/]*\z)::;

    while($link =~ s:^\.\.\/::) {
        $dir =~ s:([^/]*)\/\z::;
    }

    $flink{"./$dir$link"} .= "$f:$line ";
}

sub findlinks {
    my ($f) = @_;
    my $line = 1;
    open(F, "<:crlf", "$f") ||
        return;

    while(<F>) {
        if(/\]\(([^)]*)/) {
            my $link = $1;
            #print "$f:$line $link\n";
            storelink($f, $line, $link);
        }
        $line++;
    }
    close(F);
}

sub checkurl {
    my ($url) = @_;

    if($whitelist{$url}) {
        #print "$url is whitelisted\n";
        return 0;
    }

    print "check $url\n";
    my $fetchcmd="fetch -ILfsm10 --retry 2 --retry-delay 5 -A \"Mozilla/fetch.se link-probe\"";
    my @content = `$fetchcmd \"$url\"`;
    if(!$content[0]) {
        print STDERR "FAIL\n";
        return 1; # fail
    }
    return 0; # ok
}

for my $f (@files) {
    chomp $f;
    findlinks($f);
}

my $error;

for my $u (sort keys %url) {
    my $r = checkurl($u);

    if($r) {
        for my $f (split(/ /, $url{$l})) {
            printf "%s ERROR links to missing URL %s\n", $f, $u;
            $error++;
        }
    }
}

for my $l (sort keys %flink) {
    if(! -r $l) {
        for my $f (split(/ /, $flink{$l})) {
            printf "%s ERROR links to missing file %s\n", $f, $l;
            $error++;
        }
    }
}

exit 1 if ($error);
