.TITLE		CURLMSG Message files
.FACILITY	CURL,1793	/PREFIX=CURL_
.SEVERITY	ERROR
.BASE		1
UNSUPPROTO		<Unsupported Protocol>				
FAILINIT		<Failed Initialisation>				
BADURLSYN		<Malformed URL Syntax>				
BADURLUSER		<Malformed URL User-part>				
BADPROXY		<Couldn't resolve proxy>			
BADHOST			<Couldn't resolve host>				
FAILHOST		<Couldn't connect to host>			
FTPUNKREPLY		<FTP Unknown server reply>			
FTPNOACC		<FTP Access denied>				
FTPUSRPW		<FTP User/Password incorrect>			
FTPBADPASS		<FTP unknown answer to PASS request>		
FTPBADUSER		<FTP unknown answer to USER request>		
FTPBADPASV		<FTP unknown answer to PASV request>		
FTPBAD227		<FTP unknown 227 reply>				
FTPBADHOST227		<FTP cannot resolve host from 227 reply>	
FTPNORECONN		<FTP Unable to reconnect to 227 Host>		
FTPNOBIN		<FTP Cannot select BINARY mode>			
PARTIALFILE		<Only a part of the file was transferred>	
FTPNORETR		<FTP Couldn't retrieve file>			
FTPWRITERR		<FTP Server reported write problems>		
FTPNOQUOTE		<FTP Quote command error>			
HTTPPNF			<HTTP page not found>				
WRITERR			<Local write error>				
BADUSER			<Username badly specified>			
FTPNOSTOR		<FTP STOR command failed>			
READERR			<Local Read error>				
OUTOFMEM		<Out of memory>					
TIMEOUT			<Operation Timed out>				
FTPNOASCII		<FTP Cannot select ASCII mode>			
FTPNOPORT		<FTP PORT command failed>			
FTPNOREST		<FTP REST command failed>			
FTPNOSIZE		<FTP SIZE command failed>			
HTTPRNGERR		<HTTP Range error>				
HTTPPOSTERR		<HTTP Post error>				
SSLNOCONN		<SSL Handshaking failed>			
FTPBADRESUME		<FTP Download resume failed>			
FILENOACC		<FILE couldn't open faile>			
LDAPNOBIND		<LDAP Bind failed>				
LDAPNOSRCH		<LDAP Search Failed>				
LDAPNOLIB		<LDAP Library not found>			
LDAPNOFUNC		<LDAP Function not found>			
ABORTCB			<Callback aborted operation>			
BADPARAM		<Internal Error, Bad parameter to function>	
BADORDER		<Internal Error, Bad function calling order>	
BADPWD			<Bad password entered>				
MNYREDIR		<Too many redirects>				
UNKTELNET		<Unknown TELNET option specified>
UNKMSG			<Unknown message (50)>
BADSSLCERT		<Remote peer's SSL certificate wasn't OK>
SRVNOERR		<The Server didn't reply anything, which here is considered an error>
MAXMSG			<This is the LAST KNOWN MESSAGE, appearantly more have been added>
.END
