/***************************************************************************
 *                                  _   _ ____  _
 *  Project                     ___| | | |  _ \| |
 *                             / __| | | | |_) | |
 *                            | (__| |_| |  _ <| |___
 *                             \___|\___/|_| \_\_____|
 *
 * Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
 *
 * This software is licensed as described in the file COPYING, which
 * you should have received as part of this distribution. The terms
 * are also available at https://curl.se/docs/copyright.html.
 *
 * You may opt to use, copy, modify, merge, publish, distribute and/or sell
 * copies of the Software, and permit persons to whom the Software is
 * furnished to do so, under the terms of the COPYING file.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 * SPDX-License-Identifier: fetch
 *
 ***************************************************************************/
#include "tool_setup.h"
#include "tool_help.h"

/*
 * DO NOT edit tool_listhelp.c manually.
 * This source file is generated with the following command in an autotools
 * build:
 *
 * "make listhelp"
 */

const struct helptxt helptext[] = {
    {"    --abstract-unix-socket <path>",
     "Connect via abstract Unix domain socket",
     FETCHHELP_CONNECTION},
    {"    --alt-svc <filename>",
     "Enable alt-svc with this cache file",
     FETCHHELP_HTTP},
    {"    --anyauth",
     "Pick any authentication method",
     FETCHHELP_HTTP | FETCHHELP_PROXY | FETCHHELP_AUTH},
    {"-a, --append",
     "Append to target file when uploading",
     FETCHHELP_FTP | FETCHHELP_SFTP},
    {"    --aws-sigv4 <provider1[:prvdr2[:reg[:srv]]]>",
     "AWS V4 signature auth",
     FETCHHELP_AUTH | FETCHHELP_HTTP},
    {"    --basic",
     "HTTP Basic Authentication",
     FETCHHELP_AUTH},
    {"    --ca-native",
     "Load CA certs from the OS",
     FETCHHELP_TLS},
    {"    --cacert <file>",
     "CA certificate to verify peer against",
     FETCHHELP_TLS},
    {"    --capath <dir>",
     "CA directory to verify peer against",
     FETCHHELP_TLS},
    {"-E, --cert <certificate[:password]>",
     "Client certificate file and password",
     FETCHHELP_TLS},
    {"    --cert-status",
     "Verify server cert status OCSP-staple",
     FETCHHELP_TLS},
    {"    --cert-type <type>",
     "Certificate type (DER/PEM/ENG/PROV/P12)",
     FETCHHELP_TLS},
    {"    --ciphers <list>",
     "TLS 1.2 (1.1, 1.0) ciphers to use",
     FETCHHELP_TLS},
    {"    --compressed",
     "Request compressed response",
     FETCHHELP_HTTP},
    {"    --compressed-ssh",
     "Enable SSH compression",
     FETCHHELP_SCP | FETCHHELP_SSH},
    {"-K, --config <file>",
     "Read config from a file",
     FETCHHELP_FETCH},
    {"    --connect-timeout <seconds>",
     "Maximum time allowed to connect",
     FETCHHELP_CONNECTION | FETCHHELP_TIMEOUT},
    {"    --connect-to <HOST1:PORT1:HOST2:PORT2>",
     "Connect to host2 instead of host1",
     FETCHHELP_CONNECTION | FETCHHELP_DNS},
    {"-C, --continue-at <offset>",
     "Resumed transfer offset",
     FETCHHELP_CONNECTION},
    {"-b, --cookie <data|filename>",
     "Send cookies from string/load from file",
     FETCHHELP_HTTP},
    {"-c, --cookie-jar <filename>",
     "Save cookies to <filename> after operation",
     FETCHHELP_HTTP},
    {"    --create-dirs",
     "Create necessary local directory hierarchy",
     FETCHHELP_OUTPUT},
    {"    --create-file-mode <mode>",
     "File mode for created files",
     FETCHHELP_SFTP | FETCHHELP_SCP | FETCHHELP_FILE | FETCHHELP_UPLOAD},
    {"    --crlf",
     "Convert LF to CRLF in upload",
     FETCHHELP_FTP | FETCHHELP_SMTP},
    {"    --crlfile <file>",
     "Certificate Revocation list",
     FETCHHELP_TLS},
    {"    --curves <list>",
     "(EC) TLS key exchange algorithms to request",
     FETCHHELP_TLS},
    {"-d, --data <data>",
     "HTTP POST data",
     FETCHHELP_IMPORTANT | FETCHHELP_HTTP | FETCHHELP_POST | FETCHHELP_UPLOAD},
    {"    --data-ascii <data>",
     "HTTP POST ASCII data",
     FETCHHELP_HTTP | FETCHHELP_POST | FETCHHELP_UPLOAD},
    {"    --data-binary <data>",
     "HTTP POST binary data",
     FETCHHELP_HTTP | FETCHHELP_POST | FETCHHELP_UPLOAD},
    {"    --data-raw <data>",
     "HTTP POST data, '@' allowed",
     FETCHHELP_HTTP | FETCHHELP_POST | FETCHHELP_UPLOAD},
    {"    --data-urlencode <data>",
     "HTTP POST data URL encoded",
     FETCHHELP_HTTP | FETCHHELP_POST | FETCHHELP_UPLOAD},
    {"    --delegation <LEVEL>",
     "GSS-API delegation permission",
     FETCHHELP_AUTH},
    {"    --digest",
     "HTTP Digest Authentication",
     FETCHHELP_PROXY | FETCHHELP_AUTH | FETCHHELP_HTTP},
    {"-q, --disable",
     "Disable .fetchrc",
     FETCHHELP_FETCH},
    {"    --disable-eprt",
     "Inhibit using EPRT or LPRT",
     FETCHHELP_FTP},
    {"    --disable-epsv",
     "Inhibit using EPSV",
     FETCHHELP_FTP},
    {"    --disallow-username-in-url",
     "Disallow username in URL",
     FETCHHELP_FETCH},
    {"    --dns-interface <interface>",
     "Interface to use for DNS requests",
     FETCHHELP_DNS},
    {"    --dns-ipv4-addr <address>",
     "IPv4 address to use for DNS requests",
     FETCHHELP_DNS},
    {"    --dns-ipv6-addr <address>",
     "IPv6 address to use for DNS requests",
     FETCHHELP_DNS},
    {"    --dns-servers <addresses>",
     "DNS server addrs to use",
     FETCHHELP_DNS},
    {"    --doh-cert-status",
     "Verify DoH server cert status OCSP-staple",
     FETCHHELP_DNS | FETCHHELP_TLS},
    {"    --doh-insecure",
     "Allow insecure DoH server connections",
     FETCHHELP_DNS | FETCHHELP_TLS},
    {"    --doh-url <URL>",
     "Resolve hostnames over DoH",
     FETCHHELP_DNS},
    {"    --dump-ca-embed",
     "Write the embedded CA bundle to standard output",
     FETCHHELP_HTTP | FETCHHELP_PROXY | FETCHHELP_TLS},
    {"-D, --dump-header <filename>",
     "Write the received headers to <filename>",
     FETCHHELP_HTTP | FETCHHELP_FTP},
    {"    --ech <config>",
     "Configure ECH",
     FETCHHELP_TLS},
    {"    --egd-file <file>",
     "EGD socket path for random data",
     FETCHHELP_DEPRECATED},
    {"    --engine <name>",
     "Crypto engine to use",
     FETCHHELP_TLS},
    {"    --etag-compare <file>",
     "Load ETag from file",
     FETCHHELP_HTTP},
    {"    --etag-save <file>",
     "Parse incoming ETag and save to a file",
     FETCHHELP_HTTP},
    {"    --expect100-timeout <seconds>",
     "How long to wait for 100-continue",
     FETCHHELP_HTTP | FETCHHELP_TIMEOUT},
    {"-f, --fail",
     "Fail fast with no output on HTTP errors",
     FETCHHELP_IMPORTANT | FETCHHELP_HTTP},
    {"    --fail-early",
     "Fail on first transfer error",
     FETCHHELP_FETCH | FETCHHELP_GLOBAL},
    {"    --fail-with-body",
     "Fail on HTTP errors but save the body",
     FETCHHELP_HTTP | FETCHHELP_OUTPUT},
    {"    --false-start",
     "Enable TLS False Start",
     FETCHHELP_TLS},
    {"-F, --form <name=content>",
     "Specify multipart MIME data",
     FETCHHELP_HTTP | FETCHHELP_UPLOAD | FETCHHELP_POST | FETCHHELP_IMAP |
         FETCHHELP_SMTP},
    {"    --form-escape",
     "Escape form fields using backslash",
     FETCHHELP_HTTP | FETCHHELP_UPLOAD | FETCHHELP_POST},
    {"    --form-string <name=string>",
     "Specify multipart MIME data",
     FETCHHELP_HTTP | FETCHHELP_UPLOAD | FETCHHELP_POST | FETCHHELP_SMTP |
         FETCHHELP_IMAP},
    {"    --ftp-account <data>",
     "Account data string",
     FETCHHELP_FTP | FETCHHELP_AUTH},
    {"    --ftp-alternative-to-user <command>",
     "String to replace USER [name]",
     FETCHHELP_FTP},
    {"    --ftp-create-dirs",
     "Create the remote dirs if not present",
     FETCHHELP_FTP | FETCHHELP_SFTP},
    {"    --ftp-method <method>",
     "Control CWD usage",
     FETCHHELP_FTP},
    {"    --ftp-pasv",
     "Send PASV/EPSV instead of PORT",
     FETCHHELP_FTP},
    {"-P, --ftp-port <address>",
     "Send PORT instead of PASV",
     FETCHHELP_FTP},
    {"    --ftp-pret",
     "Send PRET before PASV",
     FETCHHELP_FTP},
    {"    --ftp-skip-pasv-ip",
     "Skip the IP address for PASV",
     FETCHHELP_FTP},
    {"    --ftp-ssl-ccc",
     "Send CCC after authenticating",
     FETCHHELP_FTP | FETCHHELP_TLS},
    {"    --ftp-ssl-ccc-mode <active/passive>",
     "Set CCC mode",
     FETCHHELP_FTP | FETCHHELP_TLS},
    {"    --ftp-ssl-control",
     "Require TLS for login, clear for transfer",
     FETCHHELP_FTP | FETCHHELP_TLS},
    {"-G, --get",
     "Put the post data in the URL and use GET",
     FETCHHELP_HTTP},
    {"-g, --globoff",
     "Disable URL globbing with {} and []",
     FETCHHELP_FETCH},
    {"    --happy-eyeballs-timeout-ms <ms>",
     "Time for IPv6 before IPv4",
     FETCHHELP_CONNECTION | FETCHHELP_TIMEOUT},
    {"    --haproxy-clientip <ip>",
     "Set address in HAProxy PROXY",
     FETCHHELP_HTTP | FETCHHELP_PROXY},
    {"    --haproxy-protocol",
     "Send HAProxy PROXY protocol v1 header",
     FETCHHELP_HTTP | FETCHHELP_PROXY},
    {"-I, --head",
     "Show document info only",
     FETCHHELP_HTTP | FETCHHELP_FTP | FETCHHELP_FILE},
    {"-H, --header <header/@file>",
     "Pass custom header(s) to server",
     FETCHHELP_HTTP | FETCHHELP_IMAP | FETCHHELP_SMTP},
    {"-h, --help <subject>",
     "Get help for commands",
     FETCHHELP_IMPORTANT | FETCHHELP_FETCH},
    {"    --hostpubmd5 <md5>",
     "Acceptable MD5 hash of host public key",
     FETCHHELP_SFTP | FETCHHELP_SCP | FETCHHELP_SSH},
    {"    --hostpubsha256 <sha256>",
     "Acceptable SHA256 hash of host public key",
     FETCHHELP_SFTP | FETCHHELP_SCP | FETCHHELP_SSH},
    {"    --hsts <filename>",
     "Enable HSTS with this cache file",
     FETCHHELP_HTTP},
    {"    --http0.9",
     "Allow HTTP 0.9 responses",
     FETCHHELP_HTTP},
    {"-0, --http1.0",
     "Use HTTP 1.0",
     FETCHHELP_HTTP},
    {"    --http1.1",
     "Use HTTP 1.1",
     FETCHHELP_HTTP},
    {"    --http2",
     "Use HTTP/2",
     FETCHHELP_HTTP},
    {"    --http2-prior-knowledge",
     "Use HTTP 2 without HTTP/1.1 Upgrade",
     FETCHHELP_HTTP},
    {"    --http3",
     "Use HTTP v3",
     FETCHHELP_HTTP},
    {"    --http3-only",
     "Use HTTP v3 only",
     FETCHHELP_HTTP},
    {"    --ignore-content-length",
     "Ignore the size of the remote resource",
     FETCHHELP_HTTP | FETCHHELP_FTP},
    {"-k, --insecure",
     "Allow insecure server connections",
     FETCHHELP_TLS | FETCHHELP_SFTP | FETCHHELP_SCP | FETCHHELP_SSH},
    {"    --interface <name>",
     "Use network interface",
     FETCHHELP_CONNECTION},
    {"    --ip-tos <string>",
     "Set IP Type of Service or Traffic Class",
     FETCHHELP_CONNECTION},
    {"    --ipfs-gateway <URL>",
     "Gateway for IPFS",
     FETCHHELP_FETCH},
    {"-4, --ipv4",
     "Resolve names to IPv4 addresses",
     FETCHHELP_CONNECTION | FETCHHELP_DNS},
    {"-6, --ipv6",
     "Resolve names to IPv6 addresses",
     FETCHHELP_CONNECTION | FETCHHELP_DNS},
    {"    --json <data>",
     "HTTP POST JSON",
     FETCHHELP_HTTP | FETCHHELP_POST | FETCHHELP_UPLOAD},
    {"-j, --junk-session-cookies",
     "Ignore session cookies read from file",
     FETCHHELP_HTTP},
    {"    --keepalive-cnt <integer>",
     "Maximum number of keepalive probes",
     FETCHHELP_CONNECTION},
    {"    --keepalive-time <seconds>",
     "Interval time for keepalive probes",
     FETCHHELP_CONNECTION | FETCHHELP_TIMEOUT},
    {"    --key <key>",
     "Private key filename",
     FETCHHELP_TLS | FETCHHELP_SSH},
    {"    --key-type <type>",
     "Private key file type (DER/PEM/ENG)",
     FETCHHELP_TLS},
    {"    --krb <level>",
     "Enable Kerberos with security <level>",
     FETCHHELP_FTP},
    {"    --libfetch <file>",
     "Generate libfetch code for this command line",
     FETCHHELP_FETCH | FETCHHELP_GLOBAL},
    {"    --limit-rate <speed>",
     "Limit transfer speed to RATE",
     FETCHHELP_CONNECTION},
    {"-l, --list-only",
     "List only mode",
     FETCHHELP_FTP | FETCHHELP_POP3 | FETCHHELP_SFTP | FETCHHELP_FILE},
    {"    --local-port <range>",
     "Use a local port number within RANGE",
     FETCHHELP_CONNECTION},
    {"-L, --location",
     "Follow redirects",
     FETCHHELP_HTTP},
    {"    --location-trusted",
     "As --location, but send secrets to other hosts",
     FETCHHELP_HTTP | FETCHHELP_AUTH},
    {"    --login-options <options>",
     "Server login options",
     FETCHHELP_IMAP | FETCHHELP_POP3 | FETCHHELP_SMTP | FETCHHELP_AUTH |
         FETCHHELP_LDAP},
    {"    --mail-auth <address>",
     "Originator address of the original email",
     FETCHHELP_SMTP},
    {"    --mail-from <address>",
     "Mail from this address",
     FETCHHELP_SMTP},
    {"    --mail-rcpt <address>",
     "Mail to this address",
     FETCHHELP_SMTP},
    {"    --mail-rcpt-allowfails",
     "Allow RCPT TO command to fail",
     FETCHHELP_SMTP},
    {"-M, --manual",
     "Display the full manual",
     FETCHHELP_FETCH},
    {"    --max-filesize <bytes>",
     "Maximum file size to download",
     FETCHHELP_CONNECTION},
    {"    --max-redirs <num>",
     "Maximum number of redirects allowed",
     FETCHHELP_HTTP},
    {"-m, --max-time <seconds>",
     "Maximum time allowed for transfer",
     FETCHHELP_CONNECTION | FETCHHELP_TIMEOUT},
    {"    --metalink",
     "Process given URLs as metalink XML file",
     FETCHHELP_DEPRECATED},
    {"    --mptcp",
     "Enable Multipath TCP",
     FETCHHELP_CONNECTION},
    {"    --negotiate",
     "Use HTTP Negotiate (SPNEGO) authentication",
     FETCHHELP_AUTH | FETCHHELP_HTTP},
    {"-n, --netrc",
     "Must read .netrc for username and password",
     FETCHHELP_AUTH},
    {"    --netrc-file <filename>",
     "Specify FILE for netrc",
     FETCHHELP_AUTH},
    {"    --netrc-optional",
     "Use either .netrc or URL",
     FETCHHELP_AUTH},
    {"-:, --next",
     "Make next URL use separate options",
     FETCHHELP_FETCH},
    {"    --no-alpn",
     "Disable the ALPN TLS extension",
     FETCHHELP_TLS | FETCHHELP_HTTP},
    {"-N, --no-buffer",
     "Disable buffering of the output stream",
     FETCHHELP_OUTPUT},
    {"    --no-clobber",
     "Do not overwrite files that already exist",
     FETCHHELP_OUTPUT},
    {"    --no-keepalive",
     "Disable TCP keepalive on the connection",
     FETCHHELP_CONNECTION},
    {"    --no-npn",
     "Disable the NPN TLS extension",
     FETCHHELP_DEPRECATED},
    {"    --no-progress-meter",
     "Do not show the progress meter",
     FETCHHELP_VERBOSE},
    {"    --no-sessionid",
     "Disable SSL session-ID reusing",
     FETCHHELP_TLS},
    {"    --noproxy <no-proxy-list>",
     "List of hosts which do not use proxy",
     FETCHHELP_PROXY},
    {"    --ntlm",
     "HTTP NTLM authentication",
     FETCHHELP_AUTH | FETCHHELP_HTTP},
    {"    --ntlm-wb",
     "HTTP NTLM authentication with winbind",
     FETCHHELP_DEPRECATED},
    {"    --oauth2-bearer <token>",
     "OAuth 2 Bearer Token",
     FETCHHELP_AUTH | FETCHHELP_IMAP | FETCHHELP_POP3 | FETCHHELP_SMTP |
         FETCHHELP_LDAP},
    {"-o, --output <file>",
     "Write to file instead of stdout",
     FETCHHELP_IMPORTANT | FETCHHELP_OUTPUT},
    {"    --output-dir <dir>",
     "Directory to save files in",
     FETCHHELP_OUTPUT},
    {"-Z, --parallel",
     "Perform transfers in parallel",
     FETCHHELP_CONNECTION | FETCHHELP_FETCH | FETCHHELP_GLOBAL},
    {"    --parallel-immediate",
     "Do not wait for multiplexing",
     FETCHHELP_CONNECTION | FETCHHELP_FETCH | FETCHHELP_GLOBAL},
    {"    --parallel-max <num>",
     "Maximum concurrency for parallel transfers",
     FETCHHELP_CONNECTION | FETCHHELP_FETCH | FETCHHELP_GLOBAL},
    {"    --pass <phrase>",
     "Passphrase for the private key",
     FETCHHELP_SSH | FETCHHELP_TLS | FETCHHELP_AUTH},
    {"    --path-as-is",
     "Do not squash .. sequences in URL path",
     FETCHHELP_FETCH},
    {"    --pinnedpubkey <hashes>",
     "Public key to verify peer against",
     FETCHHELP_TLS},
    {"    --post301",
     "Do not switch to GET after a 301 redirect",
     FETCHHELP_HTTP | FETCHHELP_POST},
    {"    --post302",
     "Do not switch to GET after a 302 redirect",
     FETCHHELP_HTTP | FETCHHELP_POST},
    {"    --post303",
     "Do not switch to GET after a 303 redirect",
     FETCHHELP_HTTP | FETCHHELP_POST},
    {"    --preproxy [protocol://]host[:port]",
     "Use this proxy first",
     FETCHHELP_PROXY},
    {"-#, --progress-bar",
     "Display transfer progress as a bar",
     FETCHHELP_VERBOSE | FETCHHELP_GLOBAL},
    {"    --proto <protocols>",
     "Enable/disable PROTOCOLS",
     FETCHHELP_CONNECTION | FETCHHELP_FETCH},
    {"    --proto-default <protocol>",
     "Use PROTOCOL for any URL missing a scheme",
     FETCHHELP_CONNECTION | FETCHHELP_FETCH},
    {"    --proto-redir <protocols>",
     "Enable/disable PROTOCOLS on redirect",
     FETCHHELP_CONNECTION | FETCHHELP_FETCH},
    {"-x, --proxy [protocol://]host[:port]",
     "Use this proxy",
     FETCHHELP_PROXY},
    {"    --proxy-anyauth",
     "Pick any proxy authentication method",
     FETCHHELP_PROXY | FETCHHELP_AUTH},
    {"    --proxy-basic",
     "Use Basic authentication on the proxy",
     FETCHHELP_PROXY | FETCHHELP_AUTH},
    {"    --proxy-ca-native",
     "Load CA certs from the OS to verify proxy",
     FETCHHELP_TLS},
    {"    --proxy-cacert <file>",
     "CA certificates to verify proxy against",
     FETCHHELP_PROXY | FETCHHELP_TLS},
    {"    --proxy-capath <dir>",
     "CA directory to verify proxy against",
     FETCHHELP_PROXY | FETCHHELP_TLS},
    {"    --proxy-cert <cert[:passwd]>",
     "Set client certificate for proxy",
     FETCHHELP_PROXY | FETCHHELP_TLS},
    {"    --proxy-cert-type <type>",
     "Client certificate type for HTTPS proxy",
     FETCHHELP_PROXY | FETCHHELP_TLS},
    {"    --proxy-ciphers <list>",
     "TLS 1.2 (1.1, 1.0) ciphers to use for proxy",
     FETCHHELP_PROXY | FETCHHELP_TLS},
    {"    --proxy-crlfile <file>",
     "Set a CRL list for proxy",
     FETCHHELP_PROXY | FETCHHELP_TLS},
    {"    --proxy-digest",
     "Digest auth with the proxy",
     FETCHHELP_PROXY | FETCHHELP_TLS},
    {"    --proxy-header <header/@file>",
     "Pass custom header(s) to proxy",
     FETCHHELP_PROXY},
    {"    --proxy-http2",
     "Use HTTP/2 with HTTPS proxy",
     FETCHHELP_HTTP | FETCHHELP_PROXY},
    {"    --proxy-insecure",
     "Skip HTTPS proxy cert verification",
     FETCHHELP_PROXY | FETCHHELP_TLS},
    {"    --proxy-key <key>",
     "Private key for HTTPS proxy",
     FETCHHELP_PROXY | FETCHHELP_TLS},
    {"    --proxy-key-type <type>",
     "Private key file type for proxy",
     FETCHHELP_PROXY | FETCHHELP_TLS},
    {"    --proxy-negotiate",
     "HTTP Negotiate (SPNEGO) auth with the proxy",
     FETCHHELP_PROXY | FETCHHELP_AUTH},
    {"    --proxy-ntlm",
     "NTLM authentication with the proxy",
     FETCHHELP_PROXY | FETCHHELP_AUTH},
    {"    --proxy-pass <phrase>",
     "Passphrase for private key for HTTPS proxy",
     FETCHHELP_PROXY | FETCHHELP_TLS | FETCHHELP_AUTH},
    {"    --proxy-pinnedpubkey <hashes>",
     "FILE/HASHES public key to verify proxy with",
     FETCHHELP_PROXY | FETCHHELP_TLS},
    {"    --proxy-service-name <name>",
     "SPNEGO proxy service name",
     FETCHHELP_PROXY | FETCHHELP_TLS},
    {"    --proxy-ssl-allow-beast",
     "Allow this security flaw for HTTPS proxy",
     FETCHHELP_PROXY | FETCHHELP_TLS},
    {"    --proxy-ssl-auto-client-cert",
     "Auto client certificate for proxy",
     FETCHHELP_PROXY | FETCHHELP_TLS},
    {"    --proxy-tls13-ciphers <list>",
     "TLS 1.3 proxy cipher suites",
     FETCHHELP_PROXY | FETCHHELP_TLS},
    {"    --proxy-tlsauthtype <type>",
     "TLS authentication type for HTTPS proxy",
     FETCHHELP_PROXY | FETCHHELP_TLS | FETCHHELP_AUTH},
    {"    --proxy-tlspassword <string>",
     "TLS password for HTTPS proxy",
     FETCHHELP_PROXY | FETCHHELP_TLS | FETCHHELP_AUTH},
    {"    --proxy-tlsuser <name>",
     "TLS username for HTTPS proxy",
     FETCHHELP_PROXY | FETCHHELP_TLS | FETCHHELP_AUTH},
    {"    --proxy-tlsv1",
     "TLSv1 for HTTPS proxy",
     FETCHHELP_PROXY | FETCHHELP_TLS | FETCHHELP_AUTH},
    {"-U, --proxy-user <user:password>",
     "Proxy user and password",
     FETCHHELP_PROXY | FETCHHELP_AUTH},
    {"    --proxy1.0 <host[:port]>",
     "Use HTTP/1.0 proxy on given port",
     FETCHHELP_PROXY},
    {"-p, --proxytunnel",
     "HTTP proxy tunnel (using CONNECT)",
     FETCHHELP_PROXY},
    {"    --pubkey <key>",
     "SSH Public key filename",
     FETCHHELP_SFTP | FETCHHELP_SCP | FETCHHELP_SSH | FETCHHELP_AUTH},
    {"-Q, --quote <command>",
     "Send command(s) to server before transfer",
     FETCHHELP_FTP | FETCHHELP_SFTP},
    {"    --random-file <file>",
     "File for reading random data from",
     FETCHHELP_DEPRECATED},
    {"-r, --range <range>",
     "Retrieve only the bytes within RANGE",
     FETCHHELP_HTTP | FETCHHELP_FTP | FETCHHELP_SFTP | FETCHHELP_FILE},
    {"    --rate <max request rate>",
     "Request rate for serial transfers",
     FETCHHELP_CONNECTION | FETCHHELP_GLOBAL},
    {"    --raw",
     "Do HTTP raw; no transfer decoding",
     FETCHHELP_HTTP},
    {"-e, --referer <URL>",
     "Referrer URL",
     FETCHHELP_HTTP},
    {"-J, --remote-header-name",
     "Use the header-provided filename",
     FETCHHELP_OUTPUT},
    {"-O, --remote-name",
     "Write output to file named as remote file",
     FETCHHELP_IMPORTANT | FETCHHELP_OUTPUT},
    {"    --remote-name-all",
     "Use the remote filename for all URLs",
     FETCHHELP_OUTPUT},
    {"-R, --remote-time",
     "Set remote file's time on local output",
     FETCHHELP_OUTPUT},
    {"    --remove-on-error",
     "Remove output file on errors",
     FETCHHELP_OUTPUT},
    {"-X, --request <method>",
     "Specify request method to use",
     FETCHHELP_CONNECTION | FETCHHELP_POP3 | FETCHHELP_FTP | FETCHHELP_IMAP |
         FETCHHELP_SMTP},
    {"    --request-target <path>",
     "Specify the target for this request",
     FETCHHELP_HTTP},
    {"    --resolve <[+]host:port:addr[,addr]...>",
     "Resolve host+port to address",
     FETCHHELP_CONNECTION | FETCHHELP_DNS},
    {"    --retry <num>",
     "Retry request if transient problems occur",
     FETCHHELP_FETCH},
    {"    --retry-all-errors",
     "Retry all errors (with --retry)",
     FETCHHELP_FETCH},
    {"    --retry-connrefused",
     "Retry on connection refused (with --retry)",
     FETCHHELP_FETCH},
    {"    --retry-delay <seconds>",
     "Wait time between retries",
     FETCHHELP_FETCH | FETCHHELP_TIMEOUT},
    {"    --retry-max-time <seconds>",
     "Retry only within this period",
     FETCHHELP_FETCH | FETCHHELP_TIMEOUT},
    {"    --sasl-authzid <identity>",
     "Identity for SASL PLAIN authentication",
     FETCHHELP_AUTH},
    {"    --sasl-ir",
     "Initial response in SASL authentication",
     FETCHHELP_AUTH},
    {"    --service-name <name>",
     "SPNEGO service name",
     FETCHHELP_AUTH},
    {"-S, --show-error",
     "Show error even when -s is used",
     FETCHHELP_FETCH | FETCHHELP_GLOBAL},
    {"-i, --show-headers",
     "Show response headers in output",
     FETCHHELP_IMPORTANT | FETCHHELP_VERBOSE | FETCHHELP_OUTPUT},
    {"-s, --silent",
     "Silent mode",
     FETCHHELP_IMPORTANT | FETCHHELP_VERBOSE},
    {"    --skip-existing",
     "Skip download if local file already exists",
     FETCHHELP_FETCH | FETCHHELP_OUTPUT},
    {"    --socks4 <host[:port]>",
     "SOCKS4 proxy on given host + port",
     FETCHHELP_PROXY},
    {"    --socks4a <host[:port]>",
     "SOCKS4a proxy on given host + port",
     FETCHHELP_PROXY},
    {"    --socks5 <host[:port]>",
     "SOCKS5 proxy on given host + port",
     FETCHHELP_PROXY},
    {"    --socks5-basic",
     "Username/password auth for SOCKS5 proxies",
     FETCHHELP_PROXY | FETCHHELP_AUTH},
    {"    --socks5-gssapi",
     "Enable GSS-API auth for SOCKS5 proxies",
     FETCHHELP_PROXY | FETCHHELP_AUTH},
    {"    --socks5-gssapi-nec",
     "Compatibility with NEC SOCKS5 server",
     FETCHHELP_PROXY | FETCHHELP_AUTH},
    {"    --socks5-gssapi-service <name>",
     "SOCKS5 proxy service name for GSS-API",
     FETCHHELP_PROXY | FETCHHELP_AUTH},
    {"    --socks5-hostname <host[:port]>",
     "SOCKS5 proxy, pass hostname to proxy",
     FETCHHELP_PROXY},
    {"-Y, --speed-limit <speed>",
     "Stop transfers slower than this",
     FETCHHELP_CONNECTION},
    {"-y, --speed-time <seconds>",
     "Trigger 'speed-limit' abort after this time",
     FETCHHELP_CONNECTION | FETCHHELP_TIMEOUT},
    {"    --ssl",
     "Try enabling TLS",
     FETCHHELP_TLS | FETCHHELP_IMAP | FETCHHELP_POP3 | FETCHHELP_SMTP |
         FETCHHELP_LDAP},
    {"    --ssl-allow-beast",
     "Allow security flaw to improve interop",
     FETCHHELP_TLS},
    {"    --ssl-auto-client-cert",
     "Use auto client certificate (Schannel)",
     FETCHHELP_TLS},
    {"    --ssl-no-revoke",
     "Disable cert revocation checks (Schannel)",
     FETCHHELP_TLS},
    {"    --ssl-reqd",
     "Require SSL/TLS",
     FETCHHELP_TLS | FETCHHELP_IMAP | FETCHHELP_POP3 | FETCHHELP_SMTP |
         FETCHHELP_LDAP},
    {"    --ssl-revoke-best-effort",
     "Ignore missing cert CRL dist points",
     FETCHHELP_TLS},
    {"    --ssl-sessions <filename>",
     "Load/save SSL session tickets from/to this file",
     FETCHHELP_TLS},
    {"-2, --sslv2",
     "SSLv2",
     FETCHHELP_DEPRECATED},
    {"-3, --sslv3",
     "SSLv3",
     FETCHHELP_DEPRECATED},
    {"    --stderr <file>",
     "Where to redirect stderr",
     FETCHHELP_VERBOSE | FETCHHELP_GLOBAL},
    {"    --styled-output",
     "Enable styled output for HTTP headers",
     FETCHHELP_VERBOSE | FETCHHELP_GLOBAL},
    {"    --suppress-connect-headers",
     "Suppress proxy CONNECT response headers",
     FETCHHELP_PROXY},
    {"    --tcp-fastopen",
     "Use TCP Fast Open",
     FETCHHELP_CONNECTION},
    {"    --tcp-nodelay",
     "Set TCP_NODELAY",
     FETCHHELP_CONNECTION},
    {"-t, --telnet-option <opt=val>",
     "Set telnet option",
     FETCHHELP_TELNET},
    {"    --tftp-blksize <value>",
     "Set TFTP BLKSIZE option",
     FETCHHELP_TFTP},
    {"    --tftp-no-options",
     "Do not send any TFTP options",
     FETCHHELP_TFTP},
    {"-z, --time-cond <time>",
     "Transfer based on a time condition",
     FETCHHELP_HTTP | FETCHHELP_FTP},
    {"    --tls-earlydata",
     "Allow use of TLSv1.3 early data (0RTT)",
     FETCHHELP_TLS},
    {"    --tls-max <VERSION>",
     "Maximum allowed TLS version",
     FETCHHELP_TLS},
    {"    --tls13-ciphers <list>",
     "TLS 1.3 cipher suites to use",
     FETCHHELP_TLS},
    {"    --tlsauthtype <type>",
     "TLS authentication type",
     FETCHHELP_TLS | FETCHHELP_AUTH},
    {"    --tlspassword <string>",
     "TLS password",
     FETCHHELP_TLS | FETCHHELP_AUTH},
    {"    --tlsuser <name>",
     "TLS username",
     FETCHHELP_TLS | FETCHHELP_AUTH},
    {"-1, --tlsv1",
     "TLSv1.0 or greater",
     FETCHHELP_TLS},
    {"    --tlsv1.0",
     "TLSv1.0 or greater",
     FETCHHELP_TLS},
    {"    --tlsv1.1",
     "TLSv1.1 or greater",
     FETCHHELP_TLS},
    {"    --tlsv1.2",
     "TLSv1.2 or greater",
     FETCHHELP_TLS},
    {"    --tlsv1.3",
     "TLSv1.3 or greater",
     FETCHHELP_TLS},
    {"    --tr-encoding",
     "Request compressed transfer encoding",
     FETCHHELP_HTTP},
    {"    --trace <file>",
     "Write a debug trace to FILE",
     FETCHHELP_VERBOSE | FETCHHELP_GLOBAL},
    {"    --trace-ascii <file>",
     "Like --trace, but without hex output",
     FETCHHELP_VERBOSE | FETCHHELP_GLOBAL},
    {"    --trace-config <string>",
     "Details to log in trace/verbose output",
     FETCHHELP_VERBOSE | FETCHHELP_GLOBAL},
    {"    --trace-ids",
     "Transfer + connection ids in verbose output",
     FETCHHELP_VERBOSE | FETCHHELP_GLOBAL},
    {"    --trace-time",
     "Add time stamps to trace/verbose output",
     FETCHHELP_VERBOSE | FETCHHELP_GLOBAL},
    {"    --unix-socket <path>",
     "Connect through this Unix domain socket",
     FETCHHELP_CONNECTION},
    {"-T, --upload-file <file>",
     "Transfer local FILE to destination",
     FETCHHELP_IMPORTANT | FETCHHELP_UPLOAD},
    {"    --url <url>",
     "URL to work with",
     FETCHHELP_FETCH},
    {"    --url-query <data>",
     "Add a URL query part",
     FETCHHELP_HTTP | FETCHHELP_POST | FETCHHELP_UPLOAD},
    {"-B, --use-ascii",
     "Use ASCII/text transfer",
     FETCHHELP_FTP | FETCHHELP_OUTPUT | FETCHHELP_LDAP},
    {"-u, --user <user:password>",
     "Server user and password",
     FETCHHELP_IMPORTANT | FETCHHELP_AUTH},
    {"-A, --user-agent <name>",
     "Send User-Agent <name> to server",
     FETCHHELP_IMPORTANT | FETCHHELP_HTTP},
    {"    --variable <[%]name=text/@file>",
     "Set variable",
     FETCHHELP_FETCH},
    {"-v, --verbose",
     "Make the operation more talkative",
     FETCHHELP_IMPORTANT | FETCHHELP_VERBOSE | FETCHHELP_GLOBAL},
    {"-V, --version",
     "Show version number and quit",
     FETCHHELP_IMPORTANT | FETCHHELP_FETCH},
    {"    --vlan-priority <priority>",
     "Set VLAN priority",
     FETCHHELP_CONNECTION},
    {"-w, --write-out <format>",
     "Output FORMAT after completion",
     FETCHHELP_VERBOSE},
    {"    --xattr",
     "Store metadata in extended file attributes",
     FETCHHELP_OUTPUT},
    {NULL, NULL, 0}};
