name: event-based

on:
  # Trigger the workflow on push or pull requests, but only for the
  # master branch
  push:
    branches:
    - master
    - '*/ci'
  pull_request:
    branches:
    - master

jobs:
  autotools:
    name: ${{ matrix.build.name }}
    runs-on: 'ubuntu-latest'
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        build:
        - name: event tests
          install:
          configure: --enable-debug --disable-shared --disable-threaded-resolver --enable-werror --with-libssh --with-openssl
          tflags: -n -e '!TLS-SRP'

    steps:
    - run: |
        sudo apt-get install libtool autoconf automake pkg-config stunnel4 libpsl-dev libbrotli-dev libzstd-dev libssh-dev
        sudo python3 -m pip install impacket
      name: install prereqs and impacket

    - uses: actions/checkout@v2

    - run: autoreconf -fi && ./configure ${{ matrix.build.configure }} && make V=1
      name: 'configure and build'

    - run: make V=1 test-ci
      name: 'test'
      env:
        TFLAGS: "${{ matrix.build.tflags }}"
